### ISSUE TITLE
Can't start on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by jamesmcfarland** [jagrosh/MusicBot#110]
When I start the server it gives me a file not found error, however the files exists as i copied the path and its there. Same with/without root

$sudo java -jar JMusicBot-0.1.1.jar -nogui
[INFO] Loading config: /home/ubuntu/config.txt
[main] WARN Settings - Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at java.awt.Toolkit$3.run(Toolkit.java:1636)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
        at java.awt.Color.<clinit>(Color.java:275)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:61)

**Comment by jagrosh** [comment]
Are you using OpenJDK?

**Comment by jagrosh** [comment]
Also, this part can be ignored if you've never run the bot or set any settings:
`[main] WARN Settings - Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json`

The issue you're seeing after that is likely due to using OpenJDK instead of JDK1.8 (OpenJDK is not supported)

**Comment by jamesmcfarland** [comment]
I followed the install guide by adding the repo and install oracle-java8-installer

**Comment by jamesmcfarland** [comment]
javac -version:
javac 1.8.0_151

**Comment by jamesmcfarland** [comment]
@jagrosh I've found the issue, libXrender is missing from that dir, ill try and get a copy of it and update

**Comment by jamesmcfarland** [comment]
missing libraries on 16.04, libXRender, libXtst and libxi, package names are `libxrender1`, `libxtst6` and `libxi6`
