### ISSUE TITLE
soundcloud doesn't work

### ISSUE THREAD

**Issue by ShimaNeko** [jagrosh/MusicBot#111]
> ;play https://soundcloud.com/das-cosmo/da-22-beat-prod-by-sxth
> SoundCloud
> DA$
> DA$ - 22 (Beat Prod. by sxth)
> 
> ShimaBo_OtBOT - Сегодня в 22:27
> :no_entry_sign: Error loading track. (изменено)

Help pls!

**Comment by jagrosh** [comment]
Can you provide a screenshot

**Comment by ShimaNeko** [comment]
![image](https://user-images.githubusercontent.com/26200890/34322289-3b4658b6-e834-11e7-9c23-429f207947d2.png)

**Comment by ShimaNeko** [comment]
![image](https://user-images.githubusercontent.com/26200890/34322335-5dfc667e-e835-11e7-9b8d-7edc5bf52042.png)
and search

**Comment by jagrosh** [comment]
Both of those work fine for me; is soundcloud available in the country you are hosting the bot in? Do other sources work?

**Comment by jagrosh** [comment]
Also, can you run the `about` command and confirm that you're on version `0.1.1`?

**Comment by ShimaNeko** [comment]
0.1.1 version
Location: France

**Comment by ringmatthew** [comment]
If a SoundCloud member does not have the licensing rights to release a track everywhere, they may only make it available to the countries where they have the rights to do so. As a result, the track might not be available in certain regions.

**Comment by ShimaNeko** [comment]
spinnins sessions, monstercat and etc...

**Comment by GSecurity** [comment]
Same issue here.
Soundcloud not working anymore (everything else working fine)
Error log:
`[main] INFO net.dv8tion.jda.core.JDA - Login Successful!
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.requests.WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.JDA - Finished Loading!
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.managers.AudioManager - Audio System successfully setup!
[lava-daemon-pool-info-loader-2-thread-1] WARN com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Suspicious exception for loading item https://soundcloud.com/cole-59/the-living-tombstone-five-nights-at-freddys-2-its-been-so-long-fnaf2
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading track from SoundCloud failed.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:282)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:256)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:119)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:429)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:415)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:219)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:60)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadPageConfigJson(SoundCloudAudioSourceManager.java:302)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:279)
        ... 11 more
`

**Comment by GSecurity** [comment]
@jagrosh Any clue about this issue ?
Pretty sure it's not an issue with rights as even royalty free music is not working.

**Comment by GSecurity** [comment]
Still same issue with latest 0.1.3 version.

**Comment by jagrosh** [comment]
Looking through the log, the issue appears to be: `java.net.SocketTimeoutException: Read timed out`. This means that either your connection was unstable or soundcloud was not able to deliver the resource in a timely manner. Unfortunately there is not much that can be done about this except make sure that your connection is as stable as possible and use a VPS or connection that has good connectivity with SoundCloud.

**Comment by GSecurity** [comment]
Thanks for you answer confirming it's not bot related.
Connection and server are all fine (dedicated one).
After some research related to this, I found out that soundclound  may have banned hoster's range IP without concern about customer being impacted...
Will contact them and and confirm if that's the case.

**Comment by jagrosh** [comment]
Based on discussion, I think it safe to assume that this may be an issue on Souncloud's end. Also, the [latest release](https://github.com/jagrosh/MusicBot/releases/latest) contains dependency updates that have improved soundcloud interaction as well.
