### ISSUE TITLE
bot error

### ISSUE THREAD

**Issue by toplez** [jagrosh/MusicBot#114]
help me figure out what happened

`root@NexusBot:~/jMusicBot# java -jar JMusicBot-0.1.1.jar -nogui
[INFO] Loading config: /root/jMusicBot/config.txt
[JDA RateLimit-Queue Pool - Thread 1] ERROR net.dv8tion.jda.core.requests.Requester - Requester timed out while executing a request
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:166)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:207)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:108)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:91)
        at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:314)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at net.dv8tion.jda.core.requests.RateLimiter$RateLimitThreadFactory.lambda$newThread$0(RateLimiter.java:105)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Failed to get gateway url
        at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:378)
        at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:335)
        at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:611)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:153)
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Failed to get gateway url
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:364)
        ... 3 more
Caused by: java.lang.Exception: Failed to get gateway url
        at net.dv8tion.jda.core.entities.impl.JDAImpl$1.handleResponse(JDAImpl.java:182)
        at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:164)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:209)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:207)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:108)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:91)
        at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:314)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at net.dv8tion.jda.core.requests.RateLimiter$RateLimitThreadFactory.lambda$newThread$0(RateLimiter.java:105)
        at java.lang.Thread.run(Thread.java:748)
`
thanks

**Comment by jagrosh** [comment]
What OS are you running this on, and does it have a stable network connection?

**Comment by toplez** [comment]
I using vps with ubuntu 16.04
it's suddenly happened like this, before the bot is working great
I want to report to the vps provider but I do not know where the exact problem

thanks

**Comment by jagrosh** [comment]
The error that occurred is here: `Requester timed out while executing a request`. This means that either the VPS lost connection entirely, or it had such a poor connection that it couldn't get a reply for its request. I'd recommend rebooting the VPS if the provider supports that, and if the problem persists, contact the provider that it has a poor network connection and that requests are timing out.
