### ISSUE TITLE
[Bug Report] Cannot play any YouTube tracks

### ISSUE THREAD

**Issue by SpielenmitLili** [jagrosh/MusicBot#1144]
### Bug Description

The bot is not able to find and play public YouTube videos since last restart. 
![image](https://user-images.githubusercontent.com/74246564/161845955-0101d46b-220d-489b-9747-a5ae1694f98d.png)

Console throws this error

`[22:47:21] [ERROR] [DefaultAudioPlayerManager]: Error in loading item https://www.youtube.com/watch?v=MZ1CJyEYgvI
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:220)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:232)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:228)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:99)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:64)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:42)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 5.10.0-10-amd64
  java.vendor: Oracle Corporation
  java.version: 1.8.0_252
  java.runtime.version: 1.8.0_252-b09
  java.vm.version: 25.252-b09
Caused by: java.lang.RuntimeException: Error when extracting data EID: 36814827-cfac-445e-a471-3303cd2738ff, mainJson <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:71)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:46)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:208)
        ... 16 common frames omitted
Caused by: java.lang.RuntimeException: Neither player nor playerResponse in result EID: c7c20786-b701-4881-b2f3-af4eef047c63, json <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackJsonData.fromMainResult(YoutubeTrackJsonData.java:53)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:81)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:60)
        ... 18 common frames omitted
`

### Steps to Reproduce

1. Find a video on YouTube
2. Copy the link
3. Use the play command with the link as an argument

### Expected Result

Play the given track

### Debug Output

```
System Properties:
  java.version = 1.8.0_252
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_252-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.6
  Owner = 678244990484480011
  Prefix = -
  AltPrefix = @mention
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = true
  UseEval = true
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.3.0_324
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 48
  Used Memory = 18

Discord Information:
  ID = 874594760084561960
  Guilds = 3
  Users = 2
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Zkazimm** [comment]
im also getting that error now, just started a few hours ago. feel like it might be something with discord?

**Comment by HeyItsJustFelix** [comment]
I believe it's the youtube api and not discord

**Comment by MichailiK** [comment]
I have a [fix](https://github.com/jagrosh/lavaplayer/pull/1) for this issue. The fix will be part of the next version (0.3.7) coming in the following minutes or hours.

**Comment by Leavaris** [comment]
This also just begin within the last few hours with us. it wont play any YT links and if trying to play YT playlists you get "💡 All entries in this playlist were longer than the allowed maximum (00:00)" even if that setting is set to 0 or any higher number.

**Comment by MichailiK** [comment]
0.3.7 has now been [released](https://github.com/jagrosh/MusicBot/releases/tag/0.3.7).

**Comment by Leavaris** [comment]
0.3.7 solved this issues, YT can now play single songs but trying to load up a YT playlist still errors
"💡 All entries in this playlist were longer than the allowed maximum (00:00)"

seems like a separate issues but this began happening the same moment the above YT issue began and changing the config time length has no effect

**Comment by MichailiK** [comment]
Please open a [new issue](https://github.com/jagrosh/MusicBot/issues/new) for this.
