### ISSUE TITLE
[Bug Report] system: FreeBSD

### ISSUE THREAD

**Issue by tiagocomti** [jagrosh/MusicBot#1176]
### Bug Description

java.lang.IllegalArgumentException: Unknown operating system: FreeBSD

### Steps to Reproduce

1. play a song

### Expected Result

play music

### Debug Output

[10:27:20] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$289/0x000000081d304418@44783e26
[10:27:20] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: could not detect sytem type, but system filter is com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$289/0x000000081d304418@44783e26 - assuming it does not match and skipping library.
[10:27:20] [INFO] [NativeLibraryLoader]: Native library connector: loading with filter null
[10:27:20] [ERROR] [NativeLibraryLoader]: Native library connector: loading failed.
java.lang.IllegalArgumentException: Unknown operating system: FreeBSD
	at com.sedmelluq.lava.common.natives.architecture.DefaultOperatingSystemTypes.detect(DefaultOperatingSystemTypes.java:46)
	at com.sedmelluq.lava.common.natives.architecture.SystemType.detect(SystemType.java:44)
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.detectMatchingSystemType(NativeLibraryLoader.java:180)

### Additional Info

I've been using this bot on this operating system for about 5 months

FreeBSD freebsd 11.2-RELEASE-p3 FreeBSD 11.2-RELEASE-p3 #0: Thu Sep  6 07:14:16 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Changing the volume requires JMusicBot to perform audio manipulation. It uses native libraries for this. JMusicBot doesn't have these libraries for FreeBSD at the moment.

In the meantime, keep the bot's volume to 100% with the `volume` command, and use the volume slider on Discord.

**Comment by tiagocomti** [comment]
> Changing the volume requires JMusicBot to perform audio manipulation. It uses native libraries for this. JMusicBot doesn't have these libraries for FreeBSD at the moment.
> 
> In the meantime, keep the bot's volume to 100% with the `volume` command, and use the volume slider on Discord.

Nice, i keep the volume in 100% and work for me :) thx

**Comment by mutesplash** [comment]
You can't play local MP3s because of this issue as well.  Exact same error.
