### ISSUE TITLE
[Bug Report] Bot just died

### ISSUE THREAD

**Issue by mondis1337** [jagrosh/MusicBot#1186]
### Bug Description

Out of nowhere my bot just left the channel and it can't reconnect for some reason. I don't think the problem is on my machine because my friend's bot went offline at the same time

### Steps to Reproduce

It's just like that

### Expected Result

idk play the music

### Debug Output

```
[19:35:57] [ERROR] [LocalAudioTrackExecutor]: Error in playback of uKTnMzKqkfs
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 5.11.0-1020-oracle
  java.vendor: Private Build
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-Ubuntu-120.04
  java.vm.version: 16.0.1+9-Ubuntu-120.04
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        ... 4 common frames omitted
[13:20:07] [WARN] [AudioWebSocket]: Failed to establish websocket connection to wss://rotterdam3130.discord.media:443/?v=4: OPENING_HANDSHAKE_RESPONSE_FAILURE - Failed to read an opening handshake response from the server: Read timed out
Closing connection and attempting to reconnect.
[13:29:48] [WARN] [AudioWebSocket]: Failed to establish websocket connection to wss://russia3773.discord.media:443/?v=4: OPENING_HANDSHAKE_RESPONSE_FAILURE - Failed to read an opening handshake response from the server: Read timed out
Closing connection and attempting to reconnect.
[06:43:25] [WARN] [AudioWebSocket]: Failed to establish websocket connection to wss://newark3923.discord.media:443/?v=4: SOCKET_CONNECT_ERROR - Failed to resolve hostname newark3923.discord.media:443: newark3923.discord.media: No address associated with hostname
Closing connection and attempting to reconnect.
[01:18:41] [WARN] [AudioWebSocket]: Failed to establish websocket connection to wss://russia1052.discord.media:443/?v=4: OPENING_HANDSHAKE_RESPONSE_FAILURE - Failed to read an opening handshake response from the server: Read timed out
Closing connection and attempting to reconnect.
[18:01:27] [INFO] [SoundCloudClientIdTracker]: Updating SoundCloud client ID (current is null).
[18:01:27] [INFO] [SoundCloudClientIdTracker]: Updating SoundCloud client ID succeeded, new ID is J17tQLcuqBpzoQoW2uMOhXjSY7npQnFA.
[06:28:52] [WARN] [AudioWebSocket]: Failed to establish websocket connection to wss://russia7400.discord.media:443/?v=4: OPENING_HANDSHAKE_RESPONSE_FAILURE - Failed to read an opening handshake response from the server: Read timed out
Closing connection and attempting to reconnect.
[06:29:00] [WARN] [AudioWebSocket]: Failed to establish websocket connection to wss://rotterdam4715.discord.media:443/?v=4: OPENING_HANDSHAKE_RESPONSE_FAILURE - Failed to read an opening handshake response from the server: Read timed out
Closing connection and attempting to reconnect.
[06:29:22] [WARN] [WebSocketClient]: Reconnect failed! Next attempt in 2s
[06:29:34] [WARN] [WebSocketClient]: Reconnect failed! Next attempt in 4s
[06:29:48] [WARN] [WebSocketClient]: Reconnect failed! Next attempt in 8s
[06:30:06] [WARN] [WebSocketClient]: Reconnect failed! Next attempt in 16s
[06:30:32] [WARN] [WebSocketClient]: Reconnect failed! Next attempt in 32s
[06:31:14] [WARN] [WebSocketClient]: Reconnect failed! Next attempt in 64s
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by hoangso7** [comment]
I met the same issues. The bot just went dead. :(

**Comment by mondis1337** [comment]
It seems to be a problem on discord side because almost all bots went offline

**Comment by YJSoft** [comment]
Probably related to  recent [cloudflare network disruption](https://www.cloudflarestatus.com/incidents/xvs51y9qs9dj).
