### ISSUE TITLE
[Bug Report] Error loading track from YouTube (410)

### ISSUE THREAD

**Issue by yarik2720** [jagrosh/MusicBot#1235]
### Bug Description

Some videos that requires users to login can't be played with bot

### Steps to Reproduce

1. Add to queue track that requires login, example https://www.youtube.com/watch?v=nSIPR2ZrfKQ
2. Track was added to queue
3. No errors, track was skipped

### Expected Result

Track should be played or error should be shown why it couldn't be played

### Debug Output

```log
[18:25:06] [ERROR] [LocalAudioTrackExecutor]: Error in playback of nSIPR2ZrfKQ
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-100-generic
  java.vendor: Ubuntu
  java.version: 11.0.16
  java.runtime.version: 11.0.16+8-post-Ubuntu-0ubuntu120.04
  java.vm.version: 11.0.16+8-post-Ubuntu-0ubuntu120.04
Caused by: java.lang.RuntimeException: Error when extracting data EID: b101c755-c360-41b8-b87c-8b9bb5b1d4c2, mainJson <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:71)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:46)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video info response: 410
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:227)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:98)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:60)
        ... 8 common frames omitted
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by xXbaodeptraiXx** [comment]
Hey I just got this error too, streaming music from YouTube, nothing plays and the queue is empty.

**Comment by MichailiK** [comment]
Duplicate of #1026
