### ISSUE TITLE
Unable to play songs from Youtube

### ISSUE THREAD

**Issue by ToasterLady** [jagrosh/MusicBot#133]
This suddenly started happening last week
Had no issues before but now the bot won't play songs from Youtube. It would join the channel then leave without playing the song.

I run the bot on a rpi
I didn't touch or do anything to the bot and it started happening

--------------------------------------------------------------------
```

[INFO] Loading config: /home/pi/config.txt
[main] INFO net.dv8tion.jda.core.JDA - Login Successful!
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.requests.WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.JDA - Finished Loading!
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.managers.AudioManager - Audio System successfully setup!
[lava-daemon-pool-playback-1-thread-1] ERROR com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager - Problematic YouTube player script /yts/jsbin/player-vflG9lb96/en_US/base.js detected (issue detected with script: no actions match). Dumped to /tmp/lavaplayer-yt-player-script5070495061029137462.js.
[lava-daemon-pool-playback-1-thread-1] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of GsebMOWQiYM
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /yts/jsbin/player-vflG9lb96/en_US/base.js
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:185)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:141)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getValidUrl(YoutubeSignatureCipherManager.java:100)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:99)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:60)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)

```

**Comment by jagrosh** [comment]
Please use the issue template. Your issue was solved in the latest release.
