### ISSUE TITLE
[Bug Report] Bot fails to load any media after specific video file was requested

### ISSUE THREAD

**Issue by twl-surrogate** [jagrosh/MusicBot#1393]
### Bug Description

this video loads forever and any other songs after it loads forever unless you restart the bot

### Steps to Reproduce

type [prefix]!play https://cdn.discordapp.com/attachments/913947222322872350/1121422680600629360/Screen_Recording_20230413_161747_Instagram.mp4

### Expected Result

video to play

### Debug Output

```
System Properties:
  java.version = 19.0.2
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 19
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 19.0.2+7-Ubuntu-0ubuntu322.04
  java.specification.version = 19
  os.arch = aarch64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.9
  Owner = 222193149219438593
  Prefix = v!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 91
  Used Memory = 17

Discord Information:
  ID = 824672449227522118
  Guilds = 7
  Users = 6
  ```

### Additional Info

relevant logs

```
Jun 12 21:28:10 absolutego java[813]: [21:28:10] [ERROR] [LocalAudioTrackExecutor]: Error in playback of https://cdn.discordapp.com/attachments/913947222322872350/1118003852390707230/e6821b21ed5721440d7797abde7146f2.mp4
Jun 12 21:28:10 absolutego java[813]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:51)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:53)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
Jun 12 21:28:10 absolutego java[813]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jun 12 21:28:10 absolutego java[813]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jun 12 21:28:10 absolutego java[813]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jun 12 21:28:10 absolutego java[813]:         Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
Jun 12 21:28:10 absolutego java[813]:   lavaplayer.version: 1.3.78
Jun 12 21:28:10 absolutego java[813]:   os.arch: aarch64
Jun 12 21:28:10 absolutego java[813]:   os.name: Linux
Jun 12 21:28:10 absolutego java[813]:   os.version: 5.15.0-1036-oracle
Jun 12 21:28:10 absolutego java[813]:   java.vendor: Ubuntu
Jun 12 21:28:10 absolutego java[813]:   java.version: 11.0.19
Jun 12 21:28:10 absolutego java[813]:   java.runtime.version: 11.0.19+7-post-Ubuntu-0ubuntu122.04.1
Jun 12 21:28:10 absolutego java[813]:   java.vm.version: 11.0.19+7-post-Ubuntu-0ubuntu122.04.1
Jun 12 21:28:10 absolutego java[813]: Caused by: java.lang.IllegalStateException: Configuring failed with error 8195
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder.configureRaw(AacDecoder.java:78)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder.configure(AacDecoder.java:66)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.configureDecoder(MpegAacTrackConsumer.java:91)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.common.AacPacketRouter.processInput(AacPacketRouter.java:31)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:78)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.standard.MpegStandardFileTrackProvider.provideFrames(MpegStandardFileTrackProvider.java:74)
Jun 12 21:28:10 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
Jun 12 21:28:10 absolutego java[813]:         ... 9 common frames omitted
Jun 16 13:33:16 absolutego java[813]: [13:33:16] [INFO] [SoundCloudClientIdTracker]: Updating SoundCloud client ID (current is null).
Jun 16 13:33:16 absolutego java[813]: [13:33:16] [INFO] [SoundCloudClientIdTracker]: Updating SoundCloud client ID succeeded, new ID is yRQW1CRxQZH1e1H1m3SFi4MpgSrOSikS.
Jun 21 07:15:23 absolutego java[813]: [07:15:23] [ERROR] [LocalAudioTrackExecutor]: Error in playback of ZZtYy65YQFo
Jun 21 07:15:23 absolutego java[813]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
Jun 21 07:15:23 absolutego java[813]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jun 21 07:15:23 absolutego java[813]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jun 21 07:15:23 absolutego java[813]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jun 21 07:15:23 absolutego java[813]:         Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
Jun 21 07:15:23 absolutego java[813]:   lavaplayer.version: 1.3.78
Jun 21 07:15:23 absolutego java[813]:   os.arch: aarch64
Jun 21 07:15:23 absolutego java[813]:   os.name: Linux
Jun 21 07:15:23 absolutego java[813]:   os.version: 5.15.0-1036-oracle
Jun 21 07:15:23 absolutego java[813]:   java.vendor: Ubuntu
Jun 21 07:15:23 absolutego java[813]:   java.version: 11.0.19
Jun 21 07:15:23 absolutego java[813]:   java.runtime.version: 11.0.19+7-post-Ubuntu-0ubuntu122.04.1
Jun 21 07:15:23 absolutego java[813]:   java.vm.version: 11.0.19+7-post-Ubuntu-0ubuntu122.04.1
Jun 21 07:15:23 absolutego java[813]: Caused by: java.lang.RuntimeException: Not success status code: 403
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
Jun 21 07:15:23 absolutego java[813]:         at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
Jun 21 07:15:23 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
Jun 21 07:15:23 absolutego java[813]:         ... 4 common frames omitted
Jun 21 07:18:34 absolutego java[813]: [07:18:34] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 1kgw0vubj9U
Jun 21 07:18:34 absolutego java[813]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
Jun 21 07:18:34 absolutego java[813]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jun 21 07:18:34 absolutego java[813]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jun 21 07:18:34 absolutego java[813]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jun 21 07:18:34 absolutego java[813]:         Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
Jun 21 07:18:34 absolutego java[813]:   lavaplayer.version: 1.3.78
Jun 21 07:18:34 absolutego java[813]:   os.arch: aarch64
Jun 21 07:18:34 absolutego java[813]:   os.name: Linux
Jun 21 07:18:34 absolutego java[813]:   os.version: 5.15.0-1036-oracle
Jun 21 07:18:34 absolutego java[813]:   java.vendor: Ubuntu
Jun 21 07:18:34 absolutego java[813]:   java.version: 11.0.19
Jun 21 07:18:34 absolutego java[813]:   java.runtime.version: 11.0.19+7-post-Ubuntu-0ubuntu122.04.1
Jun 21 07:18:34 absolutego java[813]:   java.vm.version: 11.0.19+7-post-Ubuntu-0ubuntu122.04.1
Jun 21 07:18:34 absolutego java[813]: Caused by: java.lang.RuntimeException: Not success status code: 403
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
Jun 21 07:18:34 absolutego java[813]:         at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
Jun 21 07:18:34 absolutego java[813]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
Jun 21 07:18:34 absolutego java[813]:         ... 4 common frames omitted
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
You’re seeing two issues/bugs:
1. YouTube videos cannot be played. This is already tracked in #1537, so check there for updates.
2. Some music files (mp3/mp4s) cannot be played. The cause for this is known, but quite technical. A fix will hopefully be available in the future. As a workaround, try to use a tool (like ffmpeg or Audacity) to convert/re-encode your audio to another format.

I’ll change the title & description of this issue to focus on the second bug.
