### ISSUE TITLE
[Bug Report] Failes to compile due to dependencies missing.

### ISSUE THREAD

**Issue by kokofixcomputers** [jagrosh/MusicBot#1686]
### Bug Description

JMusicBot failes to compile due to jda-utilites dependency not being found. This issue also appears in actions build and test. 

### Steps to Reproduce

Just look at the action's result.

### Expected Result

I expected it to compile properly without errors.

### Debug Output

eh.... this issue also appears in the actions

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by kokofixcomputers** [comment]
This was working

**Comment by kokofixcomputers** [comment]
Maybe i can compile the dependency or something

**Comment by kokofixcomputers** [comment]
@jagrosh Can you help?

**Comment by MichailiK** [comment]
As a workaround, you can clone the jda-utilities repository, build it & then run the `publishToMavenLocal` task to add your jda-utilities build to your local Maven cache.

**Comment by kokofixcomputers** [comment]
Wait how do i do that with gitpod/vscode?

**Comment by kokofixcomputers** [comment]
> As a workaround, you can clone the jda-utilities repository, build it & then run the `publishToMavenLocal` task to add your jda-utilities build to your local Maven cache.

@MichailiK Thanks for the reply. I can't seem to do this.
% ./gradlew publishToMavenLocal --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.service.ServiceCreationException: Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:816)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628)
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279)
	at org.gradle.initialization.DefaultGradleLauncherFactory.doNewInstance(DefaultGradleLauncherFactory.java:176)
	at org.gradle.initialization.DefaultGradleLauncherFactory.newInstance(DefaultGradleLauncherFactory.java:104)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:59)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:816)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628)
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279)
	at org.gradle.internal.service.scopes.BuildScopeServices.defaultScriptPluginFactory(BuildScopeServices.java:306)
	at org.gradle.internal.service.scopes.BuildScopeServices.createScriptPluginFactory(BuildScopeServices.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:814)
	... 62 more
Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class org.gradle.plugin.management.internal.DefaultPluginResolutionStrategy.
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:228)
	at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:80)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.plugin.internal.PluginUsePluginServiceRegistry$BuildScopeServices.createPluginResolutionStrategy(PluginUsePluginServiceRegistry.java:106)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:814)
	... 78 more
Caused by: org.gradle.internal.UncheckedException: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @1ab06251
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.internal.classloader.ClassLoaderUtils$LookupClassDefiner.defineClass(ClassLoaderUtils.java:142)
	at org.gradle.internal.classloader.ClassLoaderUtils.define(ClassLoaderUtils.java:92)
	at org.gradle.model.internal.asm.AsmClassGenerator.define(AsmClassGenerator.java:58)
	at org.gradle.model.internal.asm.AsmClassGenerator.define(AsmClassGenerator.java:54)
	at org.gradle.api.internal.AsmBackedClassGenerator$ClassBuilderImpl.generate(AsmBackedClassGenerator.java:978)
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:226)
	... 85 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @1ab06251
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 91 more


* Get more help at https://help.gradle.org

BUILD FAILED in 0s
ct@FamiM JDA-Utilities %

**Comment by kokofixcomputers** [comment]
ct@FamiM JDA-Utilities % java --version
openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
ct@FamiM JDA-Utilities %

**Comment by kokofixcomputers** [comment]
Alright done! now i just run and compile jmusicbot like normal right?

**Comment by kokofixcomputers** [comment]
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:ActiveProcessorCount=1
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.jagrosh:JMusicBot >------------------------
[INFO] Building JMusicBot Snapshot
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.jagrosh:jda-utilities:jar:3.0.5 is missing, no dependency information available
[INFO] Downloading from jitpack.io: https://jitpack.io/com/github/jagrosh/JLyrics/master-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from jitpack.io: https://jitpack.io/com/github/jagrosh/JLyrics/master-SNAPSHOT/maven-metadata.xml (383 B at 719 B/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.182 s
[INFO] Finished at: 2024-09-10T14:48:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project JMusicBot: Could not resolve dependencies for project com.jagrosh:JMusicBot:jar:Snapshot
[ERROR] dependency: com.jagrosh:jda-utilities:jar:3.0.5 (compile)
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://nexus.velocitypowered.com/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of velocity-repo has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://jcenter.bintray.com/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jcenter has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://repo1.maven.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://m2.duncte123.dev/releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of duncte123 has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://m2.dv8tion.net/releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of dv8tion has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://jitpack.io during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jitpack.io has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://m2.duncte123.dev/releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of m2.duncte123.dev has elapsed or updates are forced
[ERROR]         com.jagrosh:jda-utilities:jar:3.0.5 was not found in https://maven.lavalink.dev/releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of arbjergDev has elapsed or updates are forced

**Comment by kokofixcomputers** [comment]
running: mvn --batch-mode verify

**Comment by kokofixcomputers** [comment]
@MichailiK This doesn't seem to work.

**Comment by kokofixcomputers** [comment]
or is there any thing else i need to run? or do i need to do something?

**Comment by tienphamzzz** [comment]
i got the same issue, this dependency do not available in this repository

**Comment by sks316** [comment]
I was wondering how long it would take for someone to point this out. It's been this way for at least a month.

**Comment by kokofixcomputers** [comment]
if both of the project were maven, the cache would definitely match up and `publishToMavenLocal` would not be required. just saying.....

**Comment by anthonybartczak** [comment]
Same here, is there a different workaround apart from `publishToMavenLocal`?

**Comment by kokofixcomputers** [comment]
I am searching for it…….

**Comment by consolejockey** [comment]
I think I found a fix. As the error states, the issue is that no built release for JDA-utilities 3.0.5 can be found. There is a fork of JDA-Utilities that has a built release. You can find [the repo here](https://github.com/Nagami-Yukki/JDA-Utilities). To fix the error while building, simply replace this dependency:

```
<dependency>
    <groupId>com.jagrosh</groupId>
    <artifactId>jda-utilities</artifactId>
    <version>3.0.5</version>
    <type>pom</type>
</dependency>
```

with the following dependency:
```
<dependency>
    <groupId>com.github.Nagami-Yukki</groupId>
    <artifactId>JDA-Utilities</artifactId>
    <version>1.0</version>
</dependency>
```

**Comment by anthonybartczak** [comment]
Can confirm that it's working, good find

**Comment by kokofixcomputers** [comment]
> Can confirm that it's working, good find

Thanks!
