### ISSUE TITLE
[Bug Report] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.

### ISSUE THREAD

**Issue by TimmehDE** [jagrosh/MusicBot#1735]
### Bug Description

I was trying to play a song from Youtube when this showed up:

URL: https://www.youtube.com/watch?v=5HFR3lnfHeM

### Steps to Reproduce

Just added the YT Link to the /play prefix.

### Expected Result

to play the youtube audio.

### Debug Output

Win 10 64-Bit

```
[ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/606a66b3/player_ias.vflset/de_DE/base.js detected (issue detected with script: no n function match). 

[00:57:43] [ERROR] [AudioHandler]: Track 5HFR3lnfHeM has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment]
Duolicate of #1588
