### ISSUE TITLE
"Problematic YouTube player script"

### ISSUE THREAD

**Issue by icylad** [jagrosh/MusicBot#1759]
### Bug Description

Error when trying to play something with the bot

### Steps to Reproduce

1. Launch the bot in CMD (it comes online with no errors)
2. type @bot play *song name*
3. Bot joins the call, then leaves straight away.

### Expected Result

Bot joins the discord voice server, and plays music.

### Debug Output

System Properties:
  java.version = 22.0.2
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 22
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 22.0.2+9-70
  java.specification.version = 22
  os.arch = amd64
  os.name = Windows 11

JMusicBot Information:
  Version = 0.4.3
  Owner = 193464761462030336
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 76
  Used Memory = 21

Discord Information:
  ID = 1086640439156813834
  Guilds = 4
  Users = 4
```

### Additional Info

This shows up in the CMD window after trying to play a song.

C:\Users\USERNAME>java -Dnogui=true -jar "C:\Bot\JMusicBot\JMusicBot-0.4.3.jar
[17:28:03] [INFO] [JMusicBot]: Loaded config from C:\Users\USERNAME\config.txt
[17:28:03] [INFO] [Settings]: serversettings.json loaded from C:\Users\USERNAME\serversettings.json
[17:28:04] [INFO] [JDA]: Login Successful!
[17:28:04] [INFO] [WebSocketClient]: Connected to WebSocket
[17:28:04] [INFO] [JDA]: Finished Loading!
[17:28:24] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/28f14d97/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\USERNAME\AppData\Local\Temp\lavaplayer-yt-player-script18240919799606127481.js
[17:28:25] [ERROR] [AudioHandler]: Track Q5a7lh1zkPY has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by gerry585** [comment]
I have the same issue, how did you fix it?

**Comment by ImDedInside-git** [comment]
Did you manage to get it fixed? I'm getting the exact same error.
Thanks

**Comment by Flashyyy69** [comment]
Same thing with me 
still looking for answers
