### ISSUE TITLE
[Bug Report] : Problematic YouTube player script /s/player/3bb1f723/player_ias.vflset/es_ES/base.js detected

### ISSUE THREAD

**Issue by ericlruby** [jagrosh/MusicBot#1783]
### Bug Description

When y try to play any song the bot connects to the channel but the doesent play anything

### Steps to Reproduce

Play any song

### Expected Result

Play songs

### Debug Output

[ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/3bb1f723/player_ias.vflset/es_ES/base.js detected (issue detected with script: no actions match). Dumped to C:\Users\eric\AppData\Local\Temp\lavaplayer-yt-player-script7268486632726946257.js
[19:09:14] [ERROR] [LocalAudioTrackExecutor]: Error in playback of wccRif2DaGs
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/3bb1f723/player_ias.vflset/es_ES/base.js
	at dev.lavalink.youtube.cipher.SignatureCipherManager.extractFromScript(SignatureCipherManager.java:235)
	at dev.lavalink.youtube.cipher.SignatureCipherManager.getCipherScript(SignatureCipherManager.java:195)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:74)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 common frames omitted
[19:09:14] [ERROR] [AudioHandler]: Track wccRif2DaGs has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/3bb1f723/player_ias.vflset/es_ES/base.js
	at dev.lavalink.youtube.cipher.SignatureCipherManager.extractFromScript(SignatureCipherManager.java:235)
	at dev.lavalink.youtube.cipher.SignatureCipherManager.getCipherScript(SignatureCipherManager.java:195)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:74)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 common frames omitted

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by bkiela** [comment]
Got the same error while trying to play youtube urls but from what my very quick and not so thorough tests shown it works fine on SoundCloud, Bandcamp and twitch

**Comment by kalmonv** [comment]
Same problem. I tested on the local Linux server and on the Windows desktop, without success.

**Comment by Djinnistorm** [comment]
Updating lavalink youtube source to latest (1.11.1) resolves this problem.

**Comment by darkseid4nk** [comment]
So I grabbed 2 different version from 2 different forks that had the version in the pom.xml updated to use 1.11.1 and it gives the same error.

**Comment by Dessolate** [comment]
I am also encountering the same error using the updated branch #1772, even with the change it still won't work.

**Comment by SeVile** [comment]
Works! But use lavalink 1.11.2

**Comment by waucey** [comment]
> Works! But use lavaplayer 1.11.2

How? I'm a Genuine noob lol

**Comment by SeVile** [comment]
> > Works! But use lavaplayer 1.11.2
> 
> How? I'm a Genuine noob lol

Compile with the specified changes using maven.

**Comment by SeVile** [comment]
> > Works! But use lavaplayer 1.11.2
> 
> How? I'm a Genuine noob lol

[https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2](https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2)

**Comment by dani-nagy** [comment]
> > > Works! But use lavaplayer 1.11.2
> > 
> > 
> > How? I'm a Genuine noob lol
> 
> https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2

Thank you, this worked!

**Comment by waucey** [comment]
> > > Works! But use lavaplayer 1.11.2
> > 
> > 
> > How? I'm a Genuine noob lol
> 
> https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2

Actually my hero, also finally figured out docker too in the process LOL

**Comment by Killstreaks-lab** [comment]
I think i did something wrong because the bot still isnt working with youtube and Ive installed docker, added the ytpotoken and ytvisitordata to the congig.txt and entered in the tokens that i got and its still not working. Anyone got a screenshot of how its supposed to look in the config.txt or like a video showing how to do it?

**Comment by FaNt4zMa** [comment]
@Killstreaks-lab You downloaded 0.4.3.2 from Sevile's fork? Mine works just fine. Heres what my config.txt looks like
![image](https://github.com/user-attachments/assets/f33110fa-dae1-4e43-bb5e-82abf5f2da41)

I just added it to the end and everything worked right away

**Comment by Killstreaks-lab** [comment]
Has there been a small update because mine is just 0.4.3 not 0.4.3.2, mine could be slightly outdated I'll have to check when I get home

**Comment by FaNt4zMa** [comment]
No, 0.4.3.2 is a fork from another user in this thread. If you scrolled up a bit, the link is posted like 3 times already

**Comment by Killstreaks-lab** [comment]
Thanks alot I'm gonna grab it today when I get home and see if that works appreciate the help

**Comment by Killstreaks-lab** [comment]
> No, 0.4.3.2 is a fork from another user in this thread. If you scrolled up a bit, the link is posted like 3 times already

Yo thanks man that worked really appreciate the help

**Comment by MilanTheMan** [comment]
I set it up locally in Docker and it was working perfectly fine but when I deployed it to AWS im getting to following error: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login

**Comment by Neferiouscorte** [comment]
> > > Works! But use lavaplayer 1.11.2
> > 
> > 
> > How? I'm a Genuine noob lol
> 
> https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2

There is have any video how to do it? I just tried it but its not worked. I should be do something wrong.

**Comment by Killstreaks-lab** [comment]
> > > > Works! But use lavaplayer 1.11.2
> > > 
> > > 
> > > How? I'm a Genuine noob lol
> > 
> > 
> > https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2
> 
> There is have any video how to do it? I just tried it but its not worked. I should be do something wrong.

Did you download 0.4.3.2 from that link? Because for me I was still trying to use 0.4.3, if your still using that one even if you add the new code it still won't work

**Comment by Neferiouscorte** [comment]
> > > > > Works! But use lavaplayer 1.11.2
> > > > 
> > > > 
> > > > How? I'm a Genuine noob lol
> > > 
> > > 
> > > https://github.com/SeVile/MusicBot/releases/tag/0.4.3.2
> > 
> > 
> > There is have any video how to do it? I just tried it but its not worked. I should be do something wrong.
> 
> Did you download 0.4.3.2 from that link? Because for me I was still trying to use 0.4.3, if your still using that one even if you add the new code it still won't work

Yes mate i just removed it and installed new one, which is `0.4.3.2` its working rn. I hope bot never break down again.

**Comment by garv-shah** [comment]
> I set it up locally in Docker and it was working perfectly fine but when I deployed it to AWS im getting to following error: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login

I have the same issue, not sure how to fix it. Namely:

```
[04:27:13] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is XXXX, next update will be after 600 seconds.
[04:27:16] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of XXXX
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
[04:27:16] [ERROR] [AudioHandler]: Track XXXX has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Neferiouscorte** [comment]
Jar File not opening anymore is anybody had this issue before?

**Comment by SeVile** [comment]
> > I set it up locally in Docker and it was working perfectly fine but when I deployed it to AWS im getting to following error: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login
> 
> I have the same issue, not sure how to fix it. Namely:
> 
> ```
> [04:27:13] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is XXXX, next update will be after 600 seconds.
> [04:27:16] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of XXXX
> com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
>         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104)
>         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>         at java.base/java.lang.Thread.run(Thread.java:831)
> [04:27:16] [ERROR] [AudioHandler]: Track XXXX has failed to play
> com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
>         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104)
>         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>         at java.base/java.lang.Thread.run(Thread.java:831)
> ```

Try this
https://github.com/SeVile/MusicBot/releases/tag/0.4.3.4

**Comment by BlitzsBeast** [comment]
> > > I set it up locally in Docker and it was working perfectly fine but when I deployed it to AWS im getting to following error: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login
> > 
> > 
> > I have the same issue, not sure how to fix it. Namely:
> > ```
> > [04:27:13] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is XXXX, next update will be after 600 seconds.
> > [04:27:16] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of XXXX
> > com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
> >         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104)
> >         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
> >         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
> >         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> >         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> >         at java.base/java.lang.Thread.run(Thread.java:831)
> > [04:27:16] [ERROR] [AudioHandler]: Track XXXX has failed to play
> > com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
> >         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104)
> >         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
> >         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
> >         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> >         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> >         at java.base/java.lang.Thread.run(Thread.java:831)
> > ```
> 
> Try this https://github.com/SeVile/MusicBot/releases/tag/0.4.3.4

doesnt fix "this video requires login" issue.

**Comment by CelluloidRacer2** [comment]
> Try this https://github.com/SeVile/MusicBot/releases/tag/0.4.3.4

@SeVile your repo doesn't a section for issues, would you be able to turn it on? I understand if not

**Comment by SeVile** [comment]
> > Try this https://github.com/SeVile/MusicBot/releases/tag/0.4.3.4
> 
> @SeVile your repo doesn't a section for issues, would you be able to turn it on? I understand if not

done

**Comment by MaximBayer** [comment]
Тут вже виправлена проблема з програванням музики з YouTube просто завантажте та запустіть, більше нічого робити не треба.
https://github.com/MaximBayer/JMusicBot_UKR/releases
P.S Музичний бот переведено на Українську мову

**Comment by etas94** [comment]
> Тут вже виправлена проблема з програванням музики з YouTube простотзаван бне треа。 https://github.com/MaximBayer/JMusicBot_UKR/releases PS Музичний бот переведено на Українську мовуно на Українську мову

It works! Is there non-translated version?

**Comment by MaximBayer** [comment]
> > Тут вже виправлена проблема з програванням музики з YouTube простотзаван бне треа。 https://github.com/MaximBayer/JMusicBot_UKR/releases PS Музичний бот переведено на Українську мовуно на Українську мову
> 
> It works! Is there non-translated version?

На жаль немає, но я думаю що розробники цього проєкту побачать це виправлення, і викладуть обнову у себе англійською мовою.

**Comment by Ymmourad** [comment]
`[16:35:59] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is xxxx, next update will be after 600 seconds.
[16:36:01] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of xxxx
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:114)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
[16:36:01] [ERROR] [AudioHandler]: Track ztygmWtWCjQ has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:114)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)`

It functions locally however when running it through Digital Ocean on Centos, currently running it through digital ocean on I keep getting the same issue with "This video requires login" even on [0.4.3.4] from @SeVile. Could this be a server side issue with having the incorrect packages or libraries installed? Or possible the IP being blocked? Seems like others running it through servers like AWS are having the same issue.

**Comment by BlitzsBeast** [comment]
> Тут вже виправлена проблема з програванням музики з YouTube просто завантажте та запустіть, більше нічого робити не треба.
> https://github.com/MaximBayer/JMusicBot_UKR/releases
> P.S Музичний бот переведено на Українську мову

doesnt fix "this video requires login" issue.

**Comment by MichailiK** [comment]
In "fixed" builds of JMusicBot, login errors from YouTube means your IP is banned. You will see this message with any YouTube player from a banned IP:

![35878a76-f621-4349-9c34-64af9fb6e3a3](https://github.com/user-attachments/assets/a0bbc098-4074-4d37-b4c3-ea2bd70c237b)

YouTube has banned all the IP addresses of a bunch of popular host providers, including Hetzner, Contabo, Oracle, AWS, Google Cloud & a bunch more. You will need to use a VPN or some other Proxy to change to a not-banned IP address.

**Comment by NotHazaGaming** [comment]
> Тут вже виправлена проблема з програванням музики з YouTube просто завантажте та запустіть, більше нічого робити не треба. https://github.com/MaximBayer/JMusicBot_UKR/releases P.S Музичний бот переведено на Українську мову

is there a english version?
thank you anyway

**Comment by MaximBayer** [comment]
Я постараюсь на днях викласти виправлення на англійській версії

**Comment by MaximBayer** [comment]
> > Тут вже виправлена проблема з програванням музики з YouTube просто завантажте та запустіть, більше нічого робити не треба. https://github.com/MaximBayer/JMusicBot_UKR/releases P.S Музичний бот переведено на Українську мову
> 
> is there a english version? thank you anyway

https://github.com/MaximBayer/JMusicBot_UKR/releases/tag/0.4.3.eng

**Comment by MaximBayer** [comment]
> > Тут вже виправлена проблема з програванням музики з YouTube простотзаван бне треа。 https://github.com/MaximBayer/JMusicBot_UKR/releases PS Музичний бот переведено на Українську мовуно на Українську мову
> 
> It works! Is there non-translated version?

https://github.com/MaximBayer/JMusicBot_UKR/releases/tag/0.4.3.eng

**Comment by Hurtrex** [comment]
> > > Тут вже виправлена проблема з програванням музики з YouTube простотзаван бне треа。 https://github.com/MaximBayer/JMusicBot_UKR/releases PS Музичний бот переведено на Українську мовуно на Українську мову
> > 
> > 
> > It works! Is there non-translated version?
> 
> https://github.com/MaximBayer/JMusicBot_UKR/releases/tag/0.4.3.eng

good new abt that in the console it doesnt seem to have any error bad new is that there is no sound at all my bot has admin permission yet no sound is coming out hopefully you can help (or refer to another post that solve it cuz ive been on this for hours now)

**Comment by rojosinalma** [comment]
Did @jagrosh abbandon the project?

**Comment by MichailiK** [comment]
YouTube has made it increasingly more difficult for third parties to use their platform. I've made some progress on having JMusicBot use Google Chrome to help it get around some of the anti-bot measures YouTube recently added:

- #1772

**Comment by desw0lf** [comment]
`docker-compose` for lazy people. (tested on Always Free Oracle - OCI Ampere A1 [ARM]) 

Fixes:
1. (this issue) Problematic YouTube player script `/s/player/3bb1f723/player_ias.vflset/es_ES/base.js` detected
2. Sign in to confirm you’re not a bot - uses free **Cloudflare WARP** VPN.

_(updated 26/04/2025)_
```
services:
  jmusicbot:
    image: ghcr.io/yojoshb/jmusicbot-docker
    container_name: jmusicbot
    environment:
      - BOT_GITHUB=SeVile/MusicBot
    #  - BOT_VERSION=0.4.3.9
    volumes:
      - '$HOME/JMusicBot:/config'
    restart: unless-stopped
    network_mode: 'service:warp'
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    container_name: jmusicbot-warp
    restart: always
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY=111111111-22222222-33333333 # optional for 'plus' license
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - './data:/var/lib/cloudflare-warp'
```

**ADDITIONALLY**:
- need to create `/config/config.txt` ([instructions](https://github.com/jagrosh/MusicBot/issues/1783#issuecomment-2703274472)) ([example](https://jmusicbot.com/config/))
- need to create empty `/config/tokens.txt` file

<details>
<summary>old answer</summary>

```
services:
  jmusicbot:
    image: ghcr.io/yojoshb/jmusicbot-docker
    container_name: jmusicbot
    environment:
      - BOT_GITHUB=MaximBayer/JMusicBot_UKR
      - BOT_VERSION=0.4.3.eng
    volumes:
      - '$HOME/JMusicBot:/config'
    restart: unless-stopped
    network_mode: 'service:warp'
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    container_name: jmusicbot-warp
    restart: always
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY=111111111-22222222-33333333 # optional for 'plus' license
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - './data:/var/lib/cloudflare-warp'
```

PS: Once this (1) issue is fixed, can probably use the official .jar, so after the `BOT_GITHUB` & `BOT_VERSION` can be removed - so only the WARP will be needed to go around the (2) issue.

**References, Acknowledgments and Thanks:**
[JMusicBot fork - .jar with issue 1 fixed <comment> @MaximBayer]
</details>

![Image](https://github.com/user-attachments/assets/fa66ba46-f7c5-4bd9-8e8a-ac87914f1663)

---

**References, Acknowledgments and Thanks:**
[JMusicBot Docker @yojoshb](https://github.com/yojoshb/jmusicbot-docker/pkgs/container/jmusicbot-docker)
[JMusicBot fork @SeVille](https://github.com/SeVile/MusicBot)
[WARP solution <comment> @RooRay](https://github.com/museofficial/muse/issues/1049#issuecomment-2543918148)

**Comment by deeeeeebs** [comment]
> services:
>   jmusicbot:
>     image: ghcr.io/yojoshb/jmusicbot-docker
>     container_name: jmusicbot
>     environment:
>       - BOT_GITHUB=MaximBayer/JMusicBot_UKR
>       - BOT_VERSION=0.4.3.eng
>     volumes:
>       - '$HOME/JMusicBot:/config'

Is it just me or where is the config supposed to go?
jmusicbot    | [15:44:08] [WARN] [Config]: No token provided! Exiting.
jmusicbot    | 
jmusicbot    | Config Location: /config/config.txt


Actual location of my config is /home/myuserdir/JMusicBot/config/config.txt but it doesnt seem to find the file. I launch my docker-compose.yml file in the same directory /home/myuserdir/JMusicBot/docker-compose.yml

_I have a working setup which doesnt involve docker so the config file is working and already popuated with all the info it needs but i'm not that savvy with docker itself or how I make the docker container find the actual location of said config file.._

Any ideas?

**Comment by desw0lf** [comment]
1. Create your `config.txt` anywhere
2. Run `docker ps -a` to check the `CONTAINER_ID` of your bot
3. Copy config file from host to container `docker cp config.txt CONTAINER_ID:/config/config.txt`
4. Restart your container `docker restart CONTAINER_ID`

**Comment by deeeeeebs** [comment]
Thanks that worked!
But the bot still doesnt play songs for me?

Do I still need to supply a trusted session cookie for it to work or should it work without it?

In discord I sometimes get "this video requires login" but most of the time the bot just quickly enters and goes off again without playing anything

In the terminal log i get [10:24:51] [ERROR] [AudioHandler]: Track S7i3ugniyjg has failed to play
or
[10:24:51] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of S7i3ugniyjg


[10:23:56] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is xxxxxxxxxxxxxxxxxxxxxxxxxx(hidden), next update will be after 600 seconds.[10:23:56] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of sYPOOSIyJxU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for video failed
Caused by: java.lang.RuntimeException: Non-embeddable video cannot be loaded by embedded client


Maybe Youtube blocked Cloudlfares CIDR ranges already

**Comment by desw0lf** [comment]
> Do I still need to supply a trusted session cookie for it to work or should it work without it?

No need to supply anything else.

> But the bot still doesnt play songs for me?

Hmm, first song playback may be failing due to the retrieval of the automatic YouTube visitor id (from MaximBayer/JMusicBot_UKR). (Checked the video id and it's playing for me)

Otherwise I'm not sure why it might not be working - didn't have the `the bot just quickly enters and goes off again without playing anything` scenario happening.

// Is your Cloudflare WARP docker service working correctly?
Should say `warp=on` or `warp=plus`

[![Image](https://github.com/user-attachments/assets/d5654ee5-193d-4538-bb46-e00ec9024bc0)](https://github.com/user-attachments/assets/b5d8983e-2b03-4661-9c51-ad09c09e648e)

**Comment by deeeeeebs** [comment]
This is how it looks like on mine, different location and sliver
```
h=connectivity.cloudflareclient.com
ip=ipv6(hidden)
ts=xxxxxx
visit_scheme=https
uag=WARP for Linux
colo=FRA
sliver=010-tier1
http=http/1.1
loc=DE
tls=TLSv1.3
sni=plaintext
warp=on
gateway=off
rbi=off
kex=X25519
```

Using debian bookworm btw

NVM, so now it suddenly started working after I gave it some rest and tried again. There was one video I tried to play earlier that could'nt play because "Caused by: java.lang.RuntimeException: Non-embeddable video cannot be loaded by embedded client" but tried another one and BAM it started playing 😄 

Its not the perfect solution as we had earlier without using cookie tokens and vpn but probably the best we have for the time being. Before this I was thinking about setting up a streaming radio server and then push the youtube songs from your own pc with something like https://danielnoethen.de/butt/

Many thanks for your help and for everyone contributing!


_Update: Tried it a bit more now and its definitely more picky, some songs will give you a message "This video requires login." and another one is the one that doesn't allow playing embedded videos so your milage may vary. Also think that youtube might block your cookie ID (which is autogenerated) if you have tried playing too many blocked videos but a restart (ctrl+c and docker-compose up) will generate a new cookie ID for you and let you go again._

**Comment by AuraofMana** [comment]
Thanks everyone who has been contributing a fix to this. From what I am reading, YouTube is basically preventing 3rd party access and that's been the root cause for music not playing. The original dev is probably busy with other projects and this is not an easy problem to fix, so we haven't had an "official" update for a while. It also seems like some fixes that worked before no longer do now, as YouTube is changing stuff frequently.

This is now becoming the main thread for this problem. Can anyone more knowledgeable than me provide help w/ outlining a step-by-step current fix? I am having trouble figuring out which paths to pursue and what still works, and I am sure many others would appreciate this as well.

**Comment by AnotherRandomTech** [comment]
Came across this one when testing, an alternative option could be to download the audio and then play it back. youtube-dl or yt-dlp may be another option for this

**Comment by contact-iqbal** [comment]
Got the same error here, i use version 0.4.3,
happened to me once i use python, i remember that the youtube can't verify my system whether its a bot or human, it all ended when im trying to use my own cookie to trick youtube

<img width="1941" height="837" alt="Image" src="https://github.com/user-attachments/assets/146dbdc2-76c6-4fd0-89d4-edeee89ba34a" />
