### ISSUE TITLE
v0.2.0: nowplaying, skip, forceskip fail - null pointer exception

### ISSUE THREAD

**Issue by redblade7** [jagrosh/MusicBot#191]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [ X ] I am running the [latest version][download]: [![Release][release]][download]
- [ X ] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [ X ] I have read through the [planned and suggested features][features]

### Issue Type

- [ X ] Bug Report
- [ ] Feature Request

### Description

Replace this with a description of your bug or feature request. Please provide screenshots and logs as applicable.

Hi,

I use four JMusicBot instances on a Slackware Linux VPS. I am using the Oracle JRE from JDK v1.8.0_191.

After upgrading to 0.2.0, the commands nowplaying, skip, and forceskip display nothing in the channel, have no effect, and the server log shows errors such as this:

[22:32:40] [ERROR] [JDA]: One of the EventListeners had an uncaught exception
java.lang.NullPointerException: null
        at com.jagrosh.jmusicbot.audio.AudioHandler.getRequester(AudioHandler.java:110)
        at com.jagrosh.jmusicbot.commands.dj.ForceskipCmd.doCommand(ForceskipCmd.java:43)
        at com.jagrosh.jmusicbot.commands.MusicCommand.execute(MusicCommand.java:90)
        at com.jagrosh.jdautilities.command.Command.run(Command.java:325)
        at com.jagrosh.jdautilities.command.impl.CommandClientImpl.onMessageReceived(CommandClientImpl.java:563)
        at com.jagrosh.jdautilities.command.impl.CommandClientImpl.onEvent(CommandClientImpl.java:446)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:127)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:868)
        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:766)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:745)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:903)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by jagrosh** [comment]
I'm going to guess that the currently-playing song is from an autoplaylist?

**Comment by jagrosh** [comment]
Yeah I've realized what caused this, it will be fixed in the next update.

**Comment by jagrosh** [comment]
This should be fixed as of [0.2.1](https://github.com/jagrosh/MusicBot/releases/latest)

**Comment by redblade7** [comment]
Commands work again with 0.2.1
