### ISSUE TITLE
Bot does not start if a news type channel exists

### ISSUE THREAD

**Issue by ainomar1000** [jagrosh/MusicBot#224]
**Describe the bug**
If a server has a news channel the bot will not start and return an error

**To Reproduce**
1. Run with a server that has a news channel
2. Observe console

**Expected behavior**
Bot should start normally and not crash

**Screenshots**
`java.lang.IllegalArgumentException: Cannot create channel for type 5
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildChannel(EntityBuilder.java:251)
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuild(EntityBuilder.java:211)
        at net.dv8tion.jda.core.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:377)
        at net.dv8tion.jda.core.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:284)
        at net.dv8tion.jda.core.handle.GuildSetupNode.ensureMembers(GuildSetupNode.java:410)
        at net.dv8tion.jda.core.handle.GuildSetupNode.handleCreate(GuildSetupNode.java:243)
        at net.dv8tion.jda.core.handle.GuildSetupController.onCreate(GuildSetupController.java:185)
        at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:40)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:868)
        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:766)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:745)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:903)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

**Version Info (please complete the following information):**
 - Operating System: Windows 10 Pro
 - JMusicBot Version: 0.2.2

**Additional context**
Not sure if this also occurs when a store channel exists too, This will occur if any server the bot is in has one of these channels

**Comment by jagrosh** [comment]
This is fixed as of version 0.2.3
