### ISSUE TITLE
[Bug Report] Invalid Status Code

### ISSUE THREAD

**Issue by LubricantJam** [jagrosh/MusicBot#281]
```
14|NexusMu | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
14|NexusMu |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14|NexusMu |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14|NexusMu |    at java.lang.Thread.run(Thread.java:748)
14|NexusMu | Caused by: java.io.IOException: Invalid status code for video info response: 429
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:401)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:390)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.getTrackInfo(YoutubeAudioTrack.java:118)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:96)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
14|NexusMu |    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
14|NexusMu |    ... 4 common frames omitted

```

**Comment by jagrosh** [comment]
1. This looks like a potential issue with [lavaplayer](https://github.com/sedmelluq/lavaplayer), although the status number appears to be hitting youtube's rate limit. How many servers are playing music with the bot? Are any other services that use youtube running on the same VPS/IP address?
2. This logging doesn't look like the stock JMusicBot logs.
3. Please use the bug report template when reporting bugs.
