### ISSUE TITLE
[Bug Report] Soundcloud links won't play

### ISSUE THREAD

**Issue by Ad-Blokker** [jagrosh/MusicBot#289]
**Describe the bug**
When trying to play any soundcloud link it will spit out an error in the console

**To Reproduce**
!play https://soundcloud.com/ad-blokker/get-a-life-ian-anderson-bafbrein-warning-music

**Expected behavior**
Play some music from soundcloud

**Screenshots**
Console: https://hastebin.com/erejolisul.php

Discord output:
![image](https://user-images.githubusercontent.com/14195799/66720406-6bf0de80-edfc-11e9-97ab-ef21b1955905.png)

**Version Info (please complete the following information):**
 - Operating System: Debian 10
 - JMusicBot Version: 0.2.5

**Additional context**
Youtube and other services work just fine.

**Comment by RootAndroid58** [comment]
i think its because of token (@jagrosh ) can u update the code where we can enter our soundcloud and yt token

**Comment by MichailiK** [comment]
This seems to be a lavaplayer related issue & they are already on it. See sedmelluq/lavaplayer/pull/229

**Comment by misharyb** [comment]
I think they fixed it, but its not working yet, can we have a quick update as soon as possible.

**Comment by jagrosh** [comment]
The lavaplayer version will be updated in the next release

**Comment by Ad-Blokker** [comment]
Fixed!

**Comment by Djinnistorm** [comment]
I think this needs to be readdressed @Ad-Blokker. Is it just lavaplayer again?

**Comment by Djinnistorm** [comment]
`[20:33:33] [INFO] [SoundCloudAudioSourceManager]: Updating SoundCloud client ID (current is 2t9loNQH90kzJcsFCODdigxfp325aq4z).
[20:33:33] [INFO] [SoundCloudAudioSourceManager]: Updating SoundCloud client ID succeeded, new ID is LPqZxMy7VDZTQ0w9g4fuCdMNflDZEdIs.
[20:33:33] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$136/1534345763@445469ab
[20:33:33] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: successfully loaded.
[20:33:33] [INFO] [NativeLibraryLoader]: Native library connector: loading with filter null
[20:33:33] [INFO] [NativeLibraryLoader]: Native library connector: successfully loaded.
[20:33:34] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 179685545
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Not success status code: 401
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:169)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:185)
	at java.io.DataInputStream.readFully(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.skipIdv3Tags(Mp3TrackProvider.java:194)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:75)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.attemptLoadStream(SoundCloudAudioTrack.java:61)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:41)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	... 4 common frames omitted
`

**Comment by jagrosh** [comment]
@Djinnistorm can you share a copy of the output of the `debug` command, and also try some other soundcloud links?

**Comment by Djinnistorm** [comment]
I have tried a number of soundcloud links both new and old, none play. If they are in a queue with Youtube links they are skipped in favor of playing youtube links correctly. Here's that debug info:

[debug_information.txt](https://github.com/jagrosh/MusicBot/files/3889588/debug_information.txt)

**Comment by Djinnistorm** [comment]
@jagrosh Doesn't seem to have been temporary either, as it still doesn't work.

**Comment by Djinnistorm** [comment]
@jagrosh @Ad-Blokker I set up my bot on a different OS in a different location, still no good. I set up a fresh bot app with a fresh config file, still no good. Same error. Should this be a new ticket, or opening this one again?

**Comment by jagrosh** [comment]
No need to open a new issue just yet; I'll look into this for the next release and see if this is resolved in a lavaplayer update since the current release. If this issue, or issues similar to this, persist, I'll open a new issue consolidating information (like I've done for the ongoing youtube issues).
