### ISSUE TITLE
[Bug Report]  No configuration setting found for key 'lyrics.user-agent'      

### ISSUE THREAD

**Issue by tayron1** [jagrosh/MusicBot#297]
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'lyrics.user-agent'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
        at com.jagrosh.jlyrics.LyricsClient.<init>(LyricsClient.java:91)
        at com.jagrosh.jlyrics.LyricsClient.<init>(LyricsClient.java:55)
        at com.jagrosh.jmusicbot.commands.music.LyricsCmd.<init>(LyricsCmd.java:34)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:100)

What?

**Comment by jagrosh** [comment]
In the future, please use the bug report template.

Which jar did you download? What do you have in the `lyrics` section of your config file? Are you setting any system variables related to the config?

**Comment by jagrosh** [comment]
Closing as there's not enough information to resolve this at this time; my guess is that this came about from either an invalid config file, or a custom-built jar that was packaged incorrectly.

**Comment by victoryy2003** [comment]
PS C:\Users\victo\Documents\GitHub\MusicBot-0.3.6> java -Dnogui=true -jar MusicBot-0.3.6.jar
[21:59:22] [WARN] [Version]: There is a new version of JMusicBot available!
Current version: UNKNOWN
New Version: 0.3.6

Please visit https://github.com/jagrosh/MusicBot/releases/latest to get the latest release.
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'lyrics.user-agent'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
        at com.jagrosh.jlyrics.LyricsClient.<init>(LyricsClient.java:91)
        at com.jagrosh.jlyrics.LyricsClient.<init>(LyricsClient.java:55)
        at com.jagrosh.jmusicbot.commands.music.LyricsCmd.<init>(LyricsCmd.java:32)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:102)

**Comment by victoryy2003** [comment]
I also got this with my custom-built jar, can teach me how to package them? 
![image](https://user-images.githubusercontent.com/57824016/141794898-04735380-443e-445c-a038-7c9fcf72d57d.png)

![image](https://user-images.githubusercontent.com/57824016/141794887-451da056-a779-4bed-9b2c-47919338e7ac.png)

![image](https://user-images.githubusercontent.com/57824016/141794850-0e40ceed-0a3b-4db6-aa19-2102881dac62.png)

**Comment by victoryy2003** [comment]
@jagrosh

**Comment by victoryy2003** [comment]
It works fine if I just clicked on the start button without export as jar

![image](https://user-images.githubusercontent.com/57824016/141795202-ca1dde8a-1049-4808-80fe-abe53df96534.png)

**Comment by MichailiK** [comment]
As per the [README](https://github.com/jagrosh/MusicBot#editing), compiling or modifying the project yourself is currently not supported. Please do not comment on old issues.

**Comment by victoryy2003** [comment]
> As per the [README](https://github.com/jagrosh/MusicBot#editing), compiling or modifying the project yourself is currently not supported. Please do not comment on old issues.

May I ask is it using Maven to compile it?

**Comment by MichailiK** [comment]
This is up to you to figure out, for the aforementioned reason. Please stop bringing this up.
