### ISSUE TITLE
[Bug Report] Unable to play Youtube Mix playlists now

### ISSUE THREAD

**Issue by SRLJustin** [jagrosh/MusicBot#313]
**Describe the bug**
0.2.6 -> Now unable to play YouTube mixes (radio)

**To Reproduce**
Update to newest version, try and play a mix (radio) from YouTube

**Expected behavior**
The bot will play the mix/radio

**Screenshots**
```
[18:41:37] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://www.youtube.com/watch?v=q0hyYWKXF0Q&list=RDCLAK5uy_nomB9IIWMf7QXN3TbfmcJ5egTGzQp-JqA&start_radio=1
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Could not find tracks from mix.
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMixProvider.loadMixWithId(YoutubeMixProvider.java:98)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:249)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:228)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:91)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:133)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

[18:41] BOT The Juice: :no_entry_sign: Error loading track.

0.2.5:
[18:03] BOT The Juice: :notes: Added TONES AND I - DANCE MONKEY (OFFICIAL VIDEO) (03:56) to begin playing
:notes: Loaded 24 additional tracks!

**Comment by jagrosh** [comment]
Can you run the `debug` command and attach or paste the results here

**Comment by SRLJustin** [comment]
@jagrosh 

As requested:
```
System Properties:
  java.version = 1.8.0_201
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_201-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.6
  Owner = 133176043967217664
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.25

Runtime Information:
  Total Memory = 22
  Used Memory = 13

Discord Information:
  ID = 546858022580912140
  Guilds = 2
  Users = 119
```

**Comment by Asherlam** [comment]
@jagrosh

As requested:
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/3839264/debug_information.txt)

**Comment by Asherlam** [comment]
@jagrosh

As requested:

> System Properties:
  java.version = 11.0.4
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.4+11-post-Ubuntu-1ubuntu219.04
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.6
  Owner = 358819659581227011
  Prefix = /
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.25

Runtime Information:
  Total Memory = 127
  Used Memory = 76

Discord Information:
  ID = 605618911471468554
  Guilds = 12
  Users = 403

**Comment by NeddyPlays** [comment]
I've got the same error, my debug:

System Properties:
  java.version = 1.8.0_231
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_231-b11
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows Server 2016

JMusicBot Information:
  Version = 0.2.6
  Owner = 253644816632512513
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.25

Runtime Information:
  Total Memory = 103
  Used Memory = 28

Discord Information:
  ID = 475263858462687252
  Guilds = 4
  Users = 534

**Comment by SRLJustin** [comment]
Still an issue with 0.2.7

**Comment by xFrann** [comment]
The issues still persists, is there any progress in solving this bug?

**Comment by SRLJustin** [comment]
Issue fixed with latest lavaplayer - using snapshot for now.
