### ISSUE TITLE
Soundcloud Play

### ISSUE THREAD

**Issue by MrUnknownDE** [jagrosh/MusicBot#335]
Server-System:
Ubuntu 18.04.3 LTS x86_64 / OpenJDK 11.0.4

Hi,
There are problems with the bot when playing Soundcloud links.

**Command:**
[https://cdn.lul.ovh/KIJE4/ToyisAyO02.png](https://cdn.lul.ovh/KIJE4/ToyisAyO02.png)

**Console-Error:**
`[18:08:40] [INFO] [SoundCloudAudioSourceManager]: Updating SoundCloud client ID (current is Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA).
[18:08:40] [INFO] [SoundCloudAudioSourceManager]: Updating SoundCloud client ID succeeded, new ID is r4nH5X72hWzUcXFiXFCBs275NbNMSF8Y.
[18:08:40] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 97896221
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Not success status code: 401
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:169)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:185)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.skipIdv3Tags(Mp3TrackProvider.java:194)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:75)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.attemptLoadStream(SoundCloudAudioTrack.java:61)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:41)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 common frames omitted
`

**Comment by RaymondSchnyder** [comment]
Yo, can confirm this is an issue.

**Comment by Djinnistorm** [comment]
guess we're making a new ticket for this after all instead of talking about it on the previously closed issue. Hopefully they fix it soon...

**Comment by MrUnknownDE** [comment]
I mean, YouTube livestreams are no longer played.
[https://cdn.lul.ovh/KIJE4/colaCaTA41.png](https://cdn.lul.ovh/KIJE4/colaCaTA41.png)

**Comment by RaymondSchnyder** [comment]
How to "fix" this issue with a lil workaround:

1. clone the repo locally (`git clone https://github.com/jagrosh/MusicBot`)
2. cd into the directory (`cd MusicBot`)
3. open pom.xml with your favourite editor and go to Line 26 (vim pom.xml)
4. On this line, replace "1.3.25" with "1.3.33"
5. build it with maven. You can do that with docker for example: `docker run -it --rm --name jmusicbot-build -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install`
6. Wait for it to complete building
7. Your new compiled version will be in the "target" dir. Its the file with "All" as suffix (JMusicBot-0.2.6-All.jar).

Enjoy.

**Comment by jagrosh** [comment]
This will be resolved in the next release.

**Comment by MrUnknownDE** [comment]
btw. same server
Youtube livestream is still broken
[https://77-ec.pw/SaQa9/CUGOWuyu57.png](https://77-ec.pw/SaQa9/CUGOWuyu57.png)

**Comment by jagrosh** [comment]
This issue has gotten off-topic, and seems to be just a reiteration of the normal "sites change, so lavaplayer needs to catch up" ongoing issue.
