### ISSUE TITLE
[Feature Request] Add a setting for automatic "Now playing" information when a song starts playing

### ISSUE THREAD

**Issue by HyperGamer14** [jagrosh/MusicBot#353]
**Is your feature request related to a problem? Please describe.**
When a song starts playing the bot doesn't automatically show which one. That can be a little bit annoying when doing something else while the bot is playing in the background.

**Describe the solution you'd like**
When the bot starts a new song, it automatically posts the song title similar to the "Now playing" command

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Turn on the feature via a command like "!setautonowplaying"
2. Bot starts song
3. Bot posts "Now playing" information (Title, song length)

**Comment by jagrosh** [comment]
Although not quite the exact feature you're describing, the `nowplaying` command already continues to update - including when new songs start - assuming you have `npimages = false` in your config.

**Comment by johnb-xp** [comment]
If this was to implemented, being able to choose a "now playing" channel would be nice to reduce spam lol

**Comment by pierluigi** [comment]
I have issued `!nowplaying` however it only responds once – when the next song starts I don't get the message in the chat (only in the bot's own "Listening to ... " status message and in the text chat channel description.

**Comment by NitroXGamer1235** [comment]
my bot keeps saying on startup :
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module './config.json'
Require stack:
- C:\Users\Kids\Documents\Music Bot\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\Kids\Documents\Music Bot\index.js:2:27)
[90m    at Module._compile (internal/modules/cjs/loader.js:1156:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\Users\\Kids\\Documents\\Music Bot\\index.js'[39m ]
}
  

How Do I Fix?? hmmm any help?

**Comment by BobDaRula** [comment]
I would also love this feature. it would make this already great bot even better
