### ISSUE TITLE
Error while playing songs

### ISSUE THREAD

**Issue by Mochcin** [jagrosh/MusicBot#369]
the bot is installed on pterodactyl once it worked normally

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
:/home/container$ java -Djavax.accessibility.assistive_technologies= -Dnogui=true -jar JMusicBot.jar
[21:13:40] [INFO] [Startup]: Loaded config from /home/container/config.txt
[21:13:40] [INFO] [JDA]: Login Successful!
[21:13:41] [INFO] [WebSocketClient]: Connected to WebSocket
[21:13:41] [INFO] [JDA]: Finished Loading!
[21:14:47] [ERROR] [LocalAudioTrackExecutor]: Error in playback of UKFlFnnAwdc
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Received non-success response code 404
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
... 4 common frames omitted

**Comment by stevenschibli** [comment]
Can repro. Every youtube song fails to play on latest version.

**Comment by Mochcin** [comment]
Właśnie mi się jedna włączyła ale reszta już nie

**Comment by jagrosh** [comment]
This appears to be a change YouTube recently made, and this should be fixed in the next release. However, please be sure to use the bug report template in the future.

**Comment by TheCherry** [comment]
sorry but why is this issue closed then its not fixed yet?
