### ISSUE TITLE
[Bug Report] UnknownHostException: discordapp.com: unknown error

### ISSUE THREAD

**Issue by MonsieurPapillon** [jagrosh/MusicBot#396]
**Describe the bug**

The app throws this exception sometimes ;

```
[08:30:01] [WARN] [WebSocketClient]: Got disconnected from WebSocket. Attempting to resume session
[08:30:03] [INFO] [JDA]: Successfully resumed Session!
[10:17:44] [INFO] [Startup]: Loaded config from ****.txt
[10:59:26] [ERROR] [Requester]: There was an exception while executing a REST request
java.net.UnknownHostException: discordapp.com: unknown error
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        .....
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
        at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
This happened today, and it's the second time I've experienced it.

When this happens, the bot is unable to connect back to the discord server.

I couldn't identify if the bug happens when I lose internet (which I don't think as I can see in the logs that the app often reconnects to the web socket), or if it is indeed the host that is unreachable.

I'm running the bot on a Raspberry Pi 2, that relaunches the bot each time it reboots ; this works well.

**To Reproduce**
Run the bot for quite some time and observe when the bot can't reconnect the discord server anymore (if you have default VC it's easy to see when it is not there).

I don't know if it happens when internet is down or if it's when the host (discorpapp) has troubles.

**Expected behavior**
The app recovers from such an exception and reconnects back to the discord server

**Debug Info**
I've only access to the logs, the app was launched with nohup and I can see INFO/WARN/ERROR log levels. Or can I access the debug logs through nohup ?

I've used the bot quite a lot, I'm very satisfied with it, this is just a nitpick ;)
Thank you in advance !

**Comment by jagrosh** [comment]
This likely occurred either during a discord outage, or during an internet outage wherever the bot is being hosted. Either way, there is really no way to fix this with the current dependencies, but it may be resolved in a future update.
