### ISSUE TITLE
[Bug Report]  in YouTube search and  lavaplayer

### ISSUE THREAD

**Issue by klfdjglkfjgjffdfljgdljkgjgdfdgf** [jagrosh/MusicBot#417]
I discovered something that sometimes plays YouTube clips and sometimes no in JMusicBot
I think there is a bug in the search
Some of the names are running and others are not 
Sometimes it stops suddenly
Problems started to appear when new updates before there were no problems !
I am trying to solve a problem, but I don't think ,  it should update it

Thank you .

[09:08:25] [INFO] [JDA]: Login Successful!
[09:08:26] [INFO] [WebSocketClient]: Connected to WebSocket
[09:08:26] [INFO] [JDA]: Finished Loading!
[09:08:30] [ERROR] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message
[09:08:31] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted
[09:08:52] [ERROR] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message
[09:08:52] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted
[09:09:05] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted

**Comment by ak800i** [comment]
Same problem here

**Comment by Sanduhr32** [comment]
This issue comes from `lavaplayer`. They fixed that issue but the musicbot will feature the update in the future when it switches to the newer version of `lavaplayer`.

**Comment by klfdjglkfjgjffdfljgdljkgjgdfdgf** [comment]
Did you mean when the `lavaplayer `update is released then it updates the `musicbot `?
`We need update` because we are using this beautiful `musicbot `because it is simple
Before we had no problems using it ..
We hope he can help us , Thank you for doing your best .

**Comment by jagrosh** [comment]
This will be fixed in the next release

**Comment by klfdjglkfjgjffdfljgdljkgjgdfdgf** [comment]
Mr.jagrosh 

Thank you for your humility and responded to me . I am waiting for the update .
We support you .

**Comment by Sanduhr32** [comment]
I meant that this error already was fixed in `lavaplayer` and that the **updated** version has to be used in `musicbot`.

**Comment by klfdjglkfjgjffdfljgdljkgjgdfdgf** [comment]
oh well thank you all for helping us ..
Please close the topic to finish it.

**Comment by Djinnistorm** [comment]
Oh ok so using maven to remake referencing a newer lavaplayer will resolve the issue, thanks.

**Comment by jagrosh** [comment]
Let's keep this open until the next release is out, because a lot of people keep opening duplicates of this.

**Comment by RorickTech** [comment]
> aking project with newer version resolves issue entirely. Thanks again!

Would you provide your unofficial updated jar file with the lavaplayer library updated?

**Comment by jagrosh** [comment]
Please wait for the next release if you're not proficient with building java projects on your own, as having random jars floating around can lead to confusion and potential for malicious action.

**Comment by jagrosh** [comment]
Fixed in 0.2.9
