### ISSUE TITLE
[Bug Report] SoundCloud empty search unhandled exception

### ISSUE THREAD

**Issue by itsTurnip** [jagrosh/MusicBot#442]
**Describe the bug**
SoundCloud search command with no search results throws an unhandled exception.

**To Reproduce**
1. Do a command 'scsearch stelmakh lights', 'scsearch jose gonzales down the hillside'

**Expected behavior**
Exception should be properly handled and shown explicity to user.

**Screenshots**
```
jmusicbot_1  | [18:04:44] [WARN] [DefaultAudioPlayerManager]: Load result handler for scsearch:stelmakh lights threw an exception
jmusicbot_1  | java.lang.IllegalArgumentException: Must have at least one choice
jmusicbot_1  |  at net.dv8tion.jda.core.utils.Checks.check(Checks.java:38)
jmusicbot_1  |  at com.jagrosh.jdautilities.menu.OrderedMenu$Builder.build(OrderedMenu.java:378)
jmusicbot_1  |  at com.jagrosh.jmusicbot.commands.music.SearchCmd$ResultHandler.playlistLoaded(SearchCmd.java:130)
jmusicbot_1  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:447)
jmusicbot_1  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
jmusicbot_1  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
jmusicbot_1  |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jmusicbot_1  |  at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
jmusicbot_1  |  at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
jmusicbot_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jmusicbot_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jmusicbot_1  |  at java.lang.Thread.run(Thread.java:748)
```

**Debug Info**
```
System Properties:
  java.version = 1.8.0_242
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_242-b08
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.9
  Owner = 193336104936669184
  Prefix = .
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.49

Runtime Information:
  Total Memory = 31
  Used Memory = 18

Discord Information:
  ID = 279288721084383233
  Guilds = 6
  Users = 72
```

**Additional context**

**Comment by itsTurnip** [comment]
After tests it looks like a problem with SoundCloud API.

**Comment by Sanduhr32** [comment]
I can't even find it on soundcloud. Are you sure the tracks exist and are public?

**Comment by itsTurnip** [comment]
> 
> 
> I can't even find it on soundcloud. Are you sure the tracks exist and are public?

Hm... Song is private at the moment. It's been a long time since I opened an issue, but I think it was available earlier. I remember I could play a song by the link. 

Bot should show the message about occurred error anyways.

**Comment by MichailiK** [comment]
This issue seems stale. There have been some fixes related to SoundCloud down the line, so this should hopefully be fixed now. In case it isn't, open a new issue.
