### ISSUE TITLE
[Bug Report] Connection interruption hangs the bot.

### ISSUE THREAD

**Issue by RheaAyase** [jagrosh/MusicBot#495]
**Describe the bug**
Connection interruption hangs, the bot does not crash or exit and does not reconnect either.

**To Reproduce**
1. Run the bot
2. Pull ethernet 
3. Observe exceptions

**Expected Behavior**
The bot should crash, exit, or correctly re-connect. (Ideally exit and let the service side handle it.)

**Stack**
```
Sep 13 10:30:24 Keyra JMusicBot[1547]: java.net.UnknownHostException: discordapp.com: Name or service not known
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.Dns.lambda$static$0(Dns.java:39)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.RealCall.execute(RealCall.java:93)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.lang.Thread.run(Thread.java:748)
Sep 13 10:30:24 Keyra JMusicBot[1547]: Exception in thread "main" net.dv8tion.jda.core.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:150)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:96)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.utils.SessionControllerAdapter$1.handleResponse(SessionControllerAdapter.java:89)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:184)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:242)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.lang.Thread.run(Thread.java:748)
Sep 13 10:30:24 Keyra JMusicBot[1547]: Caused by: java.net.UnknownHostException: discordapp.com: Name or service not known
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.Dns.lambda$static$0(Dns.java:39)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at okhttp3.RealCall.execute(RealCall.java:93)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191)
Sep 13 10:30:24 Keyra JMusicBot[1547]:         ... 10 more
```

**Comment by jagrosh** [comment]
I'm guessing that this will be fixed when I update to a newer version of JDA (Discord lib); there is a fairly significant number of changes that this requires but I plan to get to it soon

**Comment by MichailiK** [comment]
JDA has been updated several times since the creation of this issue. I've just tested this myself and its safe to say its fixed.
