### ISSUE TITLE
[Bug Report] Title Here

### ISSUE THREAD

**Issue by tomoya1230** [jagrosh/MusicBot#573]
[04:51:55] [WARN] [Settings]: Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
[04:51:55] [INFO] [Startup]: Loaded config from /storage/emulated/0/Bot/config.txt                                    [04:51:56] [ERROR] [Requester]: DNS resolution failed: discord.com: Name or service not known
Exception in thread "main" net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
        at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
        at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:245)                                            at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:140)                                            at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:123)                                            at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                            at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: discord.com: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)                                                           at java.net.InetAddress.getAllByName(InetAddress.java:1126)                                                           at okhttp3.Dns.lambda$static$0(Dns.java:39)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)                                        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)                                              at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)                             at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)                                                at okhttp3.RealCall.execute(RealCall.java:93)              at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:200)                                            ... 10 more
Caused by: net.dv8tion.jda.api.exceptions.ContextException         at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)                                                 at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)                                   at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)                                 at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:623)                                              at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)                    at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:296)                                                      at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:254)                                                           at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:246)                                                           at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1918)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:182)

Please tell me how to resolve this error

**Comment by MichailiK** [comment]
`Caused by: ... discord.com: Name or service not known`
The MusicBot can't connect to Discord's servers. Check your network

**Comment by Sanduhr32** [comment]
I'm having issues with YouTube right now with their cdn or cloudflare (smiliar).

**Comment by tomoya1230** [comment]
[22:42:57] [WARN] [Settings]: Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
[22:42:57] [INFO] [Startup]: Loaded config from C:\~~\Downloads\config.txt
[22:43:18] [ERROR] [Requester]: There was an I/O error while executing a REST request: timeout
Exception in thread "main" java.util.concurrent.CompletionException: javax.security.auth.login.LoginException: When verifying the authenticity of the provided token, Discord returned an unknown response:
HTTPException[timeout]
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:623)
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:355)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:279)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:246)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1918)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:182)
Caused by: javax.security.auth.login.LoginException: When verifying the authenticity of the provided token, Discord returned an unknown response:
HTTPException[timeout]
        at net.dv8tion.jda.internal.JDAImpl$1.handleResponse(JDAImpl.java:349)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:253)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:251)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:140)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:123)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
        at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:623)
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:355)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:279)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:246)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1918)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:182)

This was returned instead
This error is displayed in the same way on two different windows

**Comment by jagrosh** [comment]
Discord recently had an outage preventing all bots from logging in

**Comment by kaomozio** [comment]
> [04:51:55] [WARN] [Settings]: Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
> [04:51:55] [INFO] [Startup]: Loaded config from /storage/emulated/0/Bot/config.txt [04:51:56] [ERROR] [Requester]: DNS resolution failed: discord.com: Name or service not known
> Exception in thread "main" net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
> at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
> at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
> at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268)
> at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
> at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:245) at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:140) at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:123) at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.net.UnknownHostException: discord.com: Name or service not known
> at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
> at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
> at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
> at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
> at java.net.InetAddress.getAllByName(InetAddress.java:1192) at java.net.InetAddress.getAllByName(InetAddress.java:1126) at okhttp3.Dns.lambda$static$0(Dns.java:39)
> at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
> at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214) at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
> at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264) at okhttp3.RealCall.execute(RealCall.java:93) at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:200) ... 10 more
> Caused by: net.dv8tion.jda.api.exceptions.ContextException at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
> at net.dv8tion.jda.api.requests.Request.(Request.java:71)
> at net.dv8tion.jda.api.requests.RestFuture.(RestFuture.java:36) at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:623) at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86) at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:296) at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:254) at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:246) at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1918)
> at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:182)
> 
what is the solution ?
