### ISSUE TITLE
[Bug Report] Soundcloud Links not working, confirmed fixed in Lavaplayer 1.3.64

### ISSUE THREAD

**Issue by Djinnistorm** [jagrosh/MusicBot#574]
Error is:
```
[19:39:30] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://soundcloud.com/user-694398002/excuse-my-rudeness-but-could-you-please-die
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:31)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Repackaging current bot source with updated Lavaplayer released today fixes the issue.

**Comment by EkilDeew** [comment]
Can you open a PR in order to get it fixed in the next release ?

**Comment by jagrosh** [comment]
There's no need to open a new PR for this, as I've already fixed it locally, so it will be in the next release.

**Comment by William00088** [comment]
> There's no need to open a new PR for this, as I've already fixed it locally, so it will be in the next release.

Hope this is as soon as possible, thank you

**Comment by jagrosh** [comment]
Resolved as of the latest release
