### ISSUE TITLE
Failed to play music lavaplayer

### ISSUE THREAD

**Issue by Nation1996** [jagrosh/MusicBot#590]
**Describe the bug**
Can't play music trough the bot 

- Windows Server 2019

**To Reproduce**
1. reinstall java https://adoptopenjdk.net/index.html (tried 8 and 11)
2. Restart Music bot
3. Shutdown and start

**Expected behavior**
Replace this text with a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem here.

**Debug Info**
[09:16:18] [INFO] [Startup]: Loaded config from D:\Bots\MC_Nassie\config.txt
[09:16:19] [INFO] [JDA]: Login Successful!
[09:16:19] [INFO] [WebSocketClient]: Connected to WebSocket
[09:16:20] [INFO] [JDA]: Finished Loading!
[09:16:48] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of 7DZsIknkKJg
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:199)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:83)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:54)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:40)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.
	... 11 common frames omitted

**Additional context**
The music bot's failed to load tracks from youtube (only links i use) 

i had no clue how to use the debug command. but i sended the information wich i got from the console.

**Comment by Nation1996** [comment]
issue fixed config
