### ISSUE TITLE
[Bug Report] Failed to play music age-restricted Youtube tracks

### ISSUE THREAD

**Issue by takenokogohan96** [jagrosh/MusicBot#622]
**Describe the bug**
Cannot play even with the latest version 0.3.3

**Repro**
command
`//play https://www.youtube.com/watch?v=6HvidkS_F7g`

![image](https://user-images.githubusercontent.com/79766963/109399447-36fc1200-7986-11eb-831a-0f2a3c7468aa.png)
"Added" is displayed, but playback does not actually start.
I've seen the same phenomenon on several other age-restricted Youtube tracks.

**Log**

```
[04:47:03] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of 6HvidkS_F7g
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:200)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:88)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.67
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 1.8.0_271
  java.runtime.version: 1.8.0_271-b09
  java.vm.version: 25.271-b09
Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.
	... 11 common frames omitted
```

**Debug Info**
This is the description of debug_information.txt obtained by the "debug" command.
```
System Properties:
  java.version = 1.8.0_271
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_271-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.3
  Owner = 117200569147457540
  Prefix = //
  AltPrefix = なし
  MaxSeconds = 1200
  NPImages = true
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_227
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.67

Runtime Information:
  Total Memory = 151
  Used Memory = 37

Discord Information:
  ID = 502395821661224970
  Guilds = 2
  Users = 5
```

My server uses this amazing bot almost every day. Thanks!

**Comment by EEE-Citra** [comment]
I believe the reason for this has to do with the fact that the bot is not and can not be signed in to YouTube (YouTube blocks age restricted videos to people who aren't signed in)
![image](https://user-images.githubusercontent.com/41847143/110501254-fc9e1d80-80c7-11eb-8b44-b51f6b7e7b15.png)

**Comment by jagrosh** [comment]
Playing age-restricted content is not supported, as it requires a sign-in (as already stated).

**Comment by weeeeelp** [comment]
Hi @jagrosh - first of all thanks for JMusicBot, it's really great. 
In regards to the HTTP 410 from Youtube on age-restricted videos - looks like there's a PR open and pending merge on Lavaplayer's repo that supposedly at least partially fixes this (one of a couple attempts to fix it already made in the past, but still - maybe it's worth a shot?):
https://github.com/sedmelluq/lavaplayer/pull/649
