### ISSUE TITLE
[Bug Report] Title Here

### ISSUE THREAD

**Issue by appto1309** [jagrosh/MusicBot#625]
**Describe the bug**
failed to load particular playlist

**To Reproduce**
1. <prefix>play <particular playlist>
ex)
[private playlist]
a!p https://youtube.com/playlist?list=PL0FRVBO2kZE7wGsPeMmWcVLxTcALyygeU
[public playlist]
a!phttps://youtube.com/playlist?list=PLn8ghr-F_yQDCWpuWJEM9z3dqnaL9VWtf

**Screenshots**
![image](https://user-images.githubusercontent.com/15155671/109855627-dfb6b400-7c9b-11eb-9ec9-33cd07aa17ad.png)

**Log**
[18:35:03] [ERROR] [DefaultAudioPlayerManager]: Error in loading item https://youtube.com/playlist?list=PL0FRVBO2kZE7wGsPeMmWcVLxTcALyygeU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.67
  os.arch: amd64
  os.name: Linux
  os.version: 4.4.59+
  java.vendor: Oracle Corporation
  java.version: 1.8.0_111
  java.runtime.version: 1.8.0_111-8u111-b14-2~bpo8+1-b14
  java.vm.version: 25.111-b14
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Invalid status code for playlist response: 404
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:58)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.playlist(YoutubeAudioSourceManager.java:243)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.playlist(YoutubeAudioSourceManager.java:228)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:70)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:42)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        ... 6 common frames omitted
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for playlist response: 404
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubePlaylistLoader.load(DefaultYoutubePlaylistLoader.java:47)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.playlist(YoutubeAudioSourceManager.java:240)
        ... 14 common frames omitted
Caused by: java.io.IOException: Invalid status code for playlist response: 404
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubePlaylistLoader.buildPlaylist(DefaultYoutubePlaylistLoader.java:100)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubePlaylistLoader.load(DefaultYoutubePlaylistLoader.java:45)
        ... 15 common frames omitted

**Debug Info**
System Properties:
  java.version = 1.8.0_111
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_111-8u111-b14-2~bpo8+1-b14
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.3
  Owner = 371933788541943812
  Prefix = a!
  AltPrefix = null
  MaxSeconds = 900
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_227
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.67

Runtime Information:
  Total Memory = 156
  Used Memory = 67

Discord Information:
  ID = 732774345121726565
  Guilds = 1
  Users = 10

**Comment by Yashinoki88** [comment]
I can load up to 100 songs but not 101 or more.

**Comment by luxus** [comment]
can confirm that bigger playlists don't load.
same playlists are fine with other music bots

**Comment by ttamnedlog** [comment]
If I understand correctly, JMusicBot uses LavaPlayer, and this issue is discussed and apparently fixed in their update: https://github.com/sedmelluq/lavaplayer/issues/591#issuecomment-792304951

I assume we'll get it soon, or someone more knowledgeable than me may be able to create a proper pull request.

**Comment by luxus** [comment]
@jagrosh maybe you could update the dependency? 
Thanks :)
