### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by AsianGames** [jagrosh/MusicBot#64]
Each time I play a playlist of youtube or just some stream from a radio, the console prints the following errors:

```
[16:19:15] [Fatal] [JDAAudioConn]: Encountered an exception:
[16:19:15] [Fatal] [JDAAudioConn]: java.io.IOException: Operation not permitted (sendto failed)
        at java.net.PlainDatagramSocketImpl.send(Native Method)
        at java.net.DatagramSocket.send(DatagramSocket.java:693)
        at net.dv8tion.jda.core.audio.factory.DefaultSendSystem$1.run(DefaultSendSystem.java:64)
```

I noob, if anyone can help me or tell me if I making a mistake, I will thank you.

Thank you very much and congratulations for the work done with this excellent bot.

**Comment by victor9401** [comment]
What is your OS?
That's a Java error. It could be, for example, caused by a blocking firewall rule, try to look in that way.

**Comment by AsianGames** [comment]
I'm testing it on a Cloud9 workspace, I think I do not have the option to modify the FW. The OS is Ubuntu.
Thank you very much for answering.

Greetings.

**Comment by victor9401** [comment]
https://community.c9.io/t/run-udp-protocol-project/9207
I think you can close issue

**Comment by AsianGames** [comment]
Thxs Again.

Closed
