### ISSUE TITLE
[Bug Report] Config.txt Error

### ISSUE THREAD

**Issue by pitardeveloper** [jagrosh/MusicBot#701]
i got this error and idk how to fix it

[WARN] [Settings]: Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
[INFO] [Startup]: Loaded config from
C:\Data\Workshop\MusicBot-master\config.txt
Exception in thread "main" net.dv8tion.jda.api.exceptions.ErrorResponseException: 0: 404: Not Found
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
        at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:256)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1931)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:181)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
        at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
        ... 7 more

**Comment by jagrosh** [comment]
Your bot was unable to reach Discord. Check your network settings, as there is nothing I can change about the bot that would fix this.
