### ISSUE TITLE
[Bug Report] Bot can't play Music from SoundCloud

### ISSUE THREAD

**Issue by 0815Cracky** [jagrosh/MusicBot#727]
**Describe the bug**
The Bot won't play Tracks and Playlists from SoundCloud any more. You add them to the Queue and nothing happens.

**To Reproduce**
1. Search a Track from SoundCloud and add them to the Queue
2. And you will get an Error "Error loading track."

**Expected behavior**
It should Play the Song or Playlist, like before.

**Log-Console**
[14:10:37] [INFO] [Startup]: Loaded config from /home/bot/config.txt
[14:10:38] [INFO] [JDA]: Login Successful!
[14:10:38] [INFO] [WebSocketClient]: Connected to WebSocket
[14:10:38] [INFO] [JDA]: Finished Loading!
[14:10:50] [INFO] [SoundCloudClientIdTracker]: Updating SoundCloud client ID (current is null).
[14:10:50] [ERROR] [SoundCloudClientIdTracker]: SoundCloud client ID update failed.
java.lang.IllegalStateException: Could not find client ID from application script.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.findClientIdFromApplicationScript(SoundCloudClientIdTracker.java:116)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.findClientIdFromSite(SoundCloudClientIdTracker.java:79)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.updateClientId(SoundCloudClientIdTracker.java:52)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.getClientId(SoundCloudClientIdTracker.java:63)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudHttpContextFilter.onRequest(SoundCloudHttpContextFilter.java:47)
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41)
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:69)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:31)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
[14:10:51] [ERROR] [LocalAudioTrackExecutor]: Error in playback of O:https://api-v2.soundcloud.com/media/soundcloud:tracks:142801498/94bed63b-9ac4-4706-bbe0-8af6ee3aa135/stream/hls
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.75
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-77-generic
  java.vendor: Oracle Corporation
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-24
  java.vm.version: 16.0.1+9-24
Caused by: java.io.IOException: Invalid status code for soundcloud stream: 401
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudHelper.loadPlaybackUrl(SoundCloudHelper.java:22)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.loadSegments(SoundCloudM3uAudioTrack.java:50)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.createSegmentTracker(SoundCloudM3uAudioTrack.java:55)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.process(SoundCloudM3uAudioTrack.java:38)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.playFromIdentifier(SoundCloudAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:38)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        ... 4 common frames omitted

**Debug Info**
```
System Properties:
  java.version = 16.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 16
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 16.0.1+9-24
  java.specification.version = 16
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.4
  Owner = 335089824568705---
  Prefix = d!
  AltPrefix = @mention
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.1_253
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.75

Runtime Information:
  Total Memory = 80
  Used Memory = 42

Discord Information:
  ID = 827602073414795---
  Guilds = 147
  Users = 912
```

**Comment by hermitoff** [comment]
Hello, we already know this problem, check this : https://github.com/jagrosh/MusicBot/issues/714

**Comment by jagrosh** [comment]
This will be fixed in the next release
