### ISSUE TITLE
The music bot does not work with 18+ YouTube videos

### ISSUE THREAD

**Issue by BigDenLog** [jagrosh/MusicBot#753]
Hello everyone. The music bot does not work with 18+ YouTube videos. After running the command, silence and error in the console. I think it is not normal. Is there a way to solve this problem?

[17:03:09] [WARN] [ExceptionTools]: Error when extracting data EID: d1968cb1-a644-489e-a348-4bbd811049c0, mainJson: (a lot of code)
[17:03:09] [ERROR] [LocalAudioTrackExecutor]: Error in playback of wk7MxC2kD7U
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.78
  os.arch: aarch64
  os.name: Linux
  os.version: 5.11.0-1016-raspi
  java.vendor: Ubuntu
  java.version: 11.0.11
  java.runtime.version: 11.0.11+9-Ubuntu-0ubuntu2
  java.vm.version: 11.0.11+9-Ubuntu-0ubuntu2
Caused by: java.lang.RuntimeException: Error when extracting data EID: d1968cb1-a644-489e-a348-4bbd811049c0, mainJson <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:71)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:46)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video info response: 410
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:227)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:98)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:60)
        ... 8 common frames omitted

**Comment by mcmcford** [comment]
i imagine there aren't any circumstances where youtube will allow you to access 18+ videos without an account and verified age (although i may be wrong)

So that would mean this bot would need access to your account / an API key connected to your account which seems out of the scope of this bots functionality or it is at least a fairly substantial change to make.

**Comment by MichailiK** [comment]
YouTube strictly blocks 18+ videos for users/IPs within the European Economic Area, and are required to sign in with an account, in which they have verified their age (using state documents for example). 18+ Videos **may** be able to be played outside the EEA.

> So that would mean this bot would need access to your account / an API key connected to your account which seems out of the scope of this bots functionality or it is at least a fairly substantial change to make.

[API Keys are not planned to be added](https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added#features-requiring-additional-api-keys), so that's indeed not an option.

**Comment by tam-carre** [comment]
Would it be possible to support YouTube cookies?

**Comment by MichailiK** [comment]
LavaPlayer deals with cookies. Cookies are, in this context, also an authorization/API token. These will, like previously mentioned, not be implemented.

**Comment by Sanduhr32** [comment]
I can recommend https://github.com/yt-dlp/yt-dlp for creating local music files if needed.
