### ISSUE TITLE
[Bug Report] java.lang.IllegalStateException: Could not acquire lock in a reasonable timeframe

### ISSUE THREAD

**Issue by babiloof** [jagrosh/MusicBot#783]
**Describe the bug**
Replace this text with a clear and concise description of what the bug is.

**To Reproduce**
When i start the bot with command "java -Dnogui=true -jar JMusicBot-0.3.5.jar" as root user i get an error
Im running Debian 9 and java version:
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-8u302-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

**Error**
[21:53:46] [WARN] [Settings]: Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
[21:53:47] [INFO] [Startup]: Loaded config from /root/JMusicBot/config.txt
Exception in thread "main" java.lang.IllegalStateException: Could not acquire lock in a reasonable timeframe! (10 seconds)
        at net.dv8tion.jda.api.utils.MiscUtil.tryLock(MiscUtil.java:169)
        at net.dv8tion.jda.api.utils.MiscUtil.locked(MiscUtil.java:131)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter.stop(BotRateLimiter.java:169)
        at net.dv8tion.jda.internal.requests.Requester.stop(Requester.java:322)
        at net.dv8tion.jda.internal.JDAImpl.shutdownInternals(JDAImpl.java:743)
        at net.dv8tion.jda.internal.JDAImpl.shutdown(JDAImpl.java:724)
        at net.dv8tion.jda.internal.JDAImpl.shutdownNow(JDAImpl.java:713)
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:380)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:301)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:268)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1870)
        at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:181)

**Comment by MichailiK** [comment]
It looks like JDA (the library that's used to connect to Discord & receive messages) shuts down while trying to login, meaning you've probably entered a wrong bot token, but it's weird that it crashes like that.

Have you made sure you've copy & pasted the bot token correctly?

**Comment by babiloof** [comment]
i did, tryed the exact same config on windows and it worked ^^

**Comment by MichailiK** [comment]
That's a really weird issue. It's difficult to figure out what's going wrong. My best guess is that either there's a network issue, or that there's a problem with your Java installation.

**Comment by MichailiK** [comment]
This issue seems to be stale/resolved. Reply if you still need help regarding this issue.

**Comment by MichailiK** [comment]
Assuming this issue is stale or resolved.

**Comment by Dan3a** [comment]
Getting the same problem,
Debian 11
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode)
