### ISSUE TITLE
Memory usage over time

### ISSUE THREAD

**Issue by thorerik** [jagrosh/MusicBot#90]
I run this bot on a relatively large server (4500 ish members), and over a fairly short amount of time, the bot started using quite obscene amounts of memory, eventually resulting in it not even playing any requests, just joining the VC and being silent. After a restart it returned to normal as if nothing was wrong.

7 day memory graph:

![image](https://static.thorerik.com/s/2017/10/23/093233.png)
The red lines are restarts, you see just before the first restart(automatic, probably a crash), it had been running reliably for at least a week (don't have the numbers I'm afraid) with a typical memory usage under 1GB.

Usage of the bot was fairly similar between the weeks.

Specs it's running on:
Docker container, unconstrained, invoked with PM2
CPU: 2x E5-2620 @ 2.00 GHz
Mem: 128GB

PM2's config:
```json
{
	"apps": [{
	  "name": "MusicBot",
	  "args": [
		  "-jar",
		  "JMusicBot-0.1.0.jar",
		  "-nogui",
		  "-Xms128m",
		  "-Xmx2048m"
	  ],
	  "script": "/usr/bin/java",
	  "node_args": [],
	  "log_date_format": "YYYY-MM-DD HH:mm Z",
	  "exec_interpreter": "none",
	  "exec_mode": "fork",
	  "env": {
		"production": true
	  }
	}]
}
```

Log just before and after restart:
```
0|MusicBot | 2017-10-18 13:33 +00:00:
0|MusicBot | [13:33:31] [Fatal] [RestAction]: java.lang.NoClassDefFoundError: javafx/util/Pair
0|MusicBot |    at com.jagrosh.jmusicbot.Bot.setLastNP(Bot.java:177)
0|MusicBot |    at com.jagrosh.jmusicbot.commands.NowplayingCmd.lambda$doCommand$0(NowplayingCmd.java:40)
0|MusicBot |    at com.jagrosh.jdautilities.commandclient.CommandEvent.lambda$reply$3(CommandEvent.java:262)
0|MusicBot |    at net.dv8tion.jda.core.requests.Request.lambda$onSuccess$17(Request.java:63)
0|MusicBot |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
0|MusicBot |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
0|MusicBot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
0|MusicBot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
0|MusicBot |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
0|MusicBot |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
0|MusicBot |    at java.lang.Thread.run(Thread.java:748)
0|MusicBot | 2017-10-18 15:44 +00:00: [15:44:37] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
0|MusicBot | 2017-10-18 15:44 +00:00: [15:44:37] [Warning] [JDASocket]: Attempting to reconnect in 2s
0|MusicBot | 2017-10-18 15:44 +00:00: [15:44:39] [Warning] [JDASocket]: Attempting to reconnect!
0|MusicBot | 2017-10-18 15:44 +00:00: [15:44:40] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-18 15:44 +00:00: [15:44:41] [Info] [JDA]: Successfully resumed Session!
0|MusicBot | 2017-10-18 17:29 +00:00: [17:29:57] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
0|MusicBot | 2017-10-18 17:29 +00:00:
0|MusicBot | [17:29:57] [Warning] [JDASocket]: Attempting to reconnect in 2s
0|MusicBot | 2017-10-18 17:29 +00:00: [17:29:59] [Warning] [JDASocket]: Attempting to reconnect!
0|MusicBot | 2017-10-18 17:30 +00:00: [17:30:00] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-18 17:30 +00:00:
0|MusicBot | 2017-10-18 17:30 +00:00: [17:30:00] [Info] [JDA]: Successfully resumed Session!
0|MusicBot | 2017-10-18 17:49 +00:00: [17:49:07] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
0|MusicBot | 2017-10-18 17:49 +00:00: [17:49:07] [Warning] [JDASocket]: Attempting to reconnect in 2s
0|MusicBot | 2017-10-18 17:49 +00:00: [17:49:09] [Warning] [JDASocket]: Attempting to reconnect!
0|MusicBot | 2017-10-18 17:49 +00:00: [17:49:09] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-18 17:49 +00:00: [17:49:10] [Info] [JDA]: Successfully resumed Session!
0|MusicBot | 2017-10-18 18:00 +00:00: [18:00:44] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
0|MusicBot | 2017-10-18 18:00 +00:00:
0|MusicBot | [18:00:44] [Warning] [JDASocket]: Attempting to reconnect in 2s
0|MusicBot | 2017-10-18 18:00 +00:00: [18:00:46] [Warning] [JDASocket]: Attempting to reconnect!
0|MusicBot | 2017-10-18 18:00 +00:00: [18:00:46] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-18 18:00 +00:00:
0|MusicBot | 2017-10-18 18:00 +00:00: [18:00:46] [Info] [JDA]: Successfully resumed Session!
0|MusicBot | 2017-10-18 18:14 +00:00: [18:14:56] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
0|MusicBot | 2017-10-18 18:14 +00:00:
0|MusicBot | [18:14:56] [Warning] [JDASocket]: Attempting to reconnect in 2s
0|MusicBot | 2017-10-18 18:14 +00:00: [18:14:58] [Warning] [JDASocket]: Attempting to reconnect!
0|MusicBot | 2017-10-18 18:14 +00:00: [18:14:59] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-18 18:14 +00:00: [18:14:59] [Info] [JDA]: Successfully resumed Session!
0|MusicBot | 2017-10-18 22:43 +00:00: [22:43:51] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
0|MusicBot | 2017-10-18 22:43 +00:00: [22:43:51] [Warning] [JDASocket]: Attempting to reconnect in 2s
0|MusicBot | 2017-10-18 22:43 +00:00: [22:43:53] [Warning] [JDASocket]: Attempting to reconnect!
0|MusicBot | 2017-10-18 22:43 +00:00: [22:43:53] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-18 22:43 +00:00:
0|MusicBot | 2017-10-18 22:43 +00:00: [22:43:53] [Info] [JDA]: Successfully resumed Session!
PM2        | Stopping app:MusicBot id:0
PM2        | pid=820 msg=failed to kill - retrying in 100ms
PM2        | pid=820 msg=failed to kill - retrying in 100ms
PM2        | pid=820 msg=failed to kill - retrying in 100ms
PM2        | App [MusicBot] with id [0] and pid [820], exited with code [130] via signal [SIGINT]
PM2        | pid=820 msg=process killed
PM2        | Starting execution sequence in -fork mode- for app name:MusicBot id:0
PM2        | App name:MusicBot id:0 online
0|MusicBot | 2017-10-23 07:26 +00:00: [INFO] Loading config: /app/config.txt
0|MusicBot | 2017-10-23 07:26 +00:00: [07:26:18] [Info] [JDA]: Login Successful!
0|MusicBot | 2017-10-23 07:26 +00:00: [07:26:18] [Info] [JDASocket]: Connected to WebSocket
0|MusicBot | 2017-10-23 07:26 +00:00: [07:26:20] [Info] [JDA]: Finished Loading!
0|MusicBot | 2017-10-23 07:26 +00:00: [07:26:42] [Info] [JDAAudioManager]: Audio System successfully setup!
```

**Comment by jagrosh** [comment]
Are you using JDK1.8 (and not OpenJDK)? Also, I believe you might actually want your args to be:
```
"args": [
		  "-jar",
		  "-Xms128m",
		  "-Xmx2048m",
		  "JMusicBot-0.1.0.jar",
		  "-nogui"
	  ]
```
(`-jar`, `-Xms`, and `-Xmx` are all JVM flags, whereas `-nogui` is a JMusicBot flag)

**Comment by thorerik** [comment]
I'll see if I can get JDK1.8 working in alpine, it's using OpenJDK, could be the issue.

I'll swap the settings around as well :+1:

**Comment by thorerik** [comment]
I'll close the issue for now, if the issue arrises again with Oracle JDK, I'll reopen.
