### ISSUE TITLE
[Bug Report] Emoji not show?

### ISSUE THREAD

**Issue by BEERZXD** [jagrosh/MusicBot#947]
### Bug Description

![image](https://user-images.githubusercontent.com/91867324/135801391-120f4183-cdb2-4124-bc75-4564c65d50f5.png)
![image](https://user-images.githubusercontent.com/91867324/135801409-3bc83b73-5437-4378-b141-93043c916244.png)
Why emoji isn't show???

### Steps to Reproduce

It show when I use command.

### Expected Result

Just want it to show!

### Debug Output

```shell
[ERROR] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10014: Unknown Emoji
net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)
        at com.jagrosh.jdautilities.command.CommandEvent.react(CommandEvent.java:910)
        at com.jagrosh.jdautilities.command.CommandEvent.reactSuccess(CommandEvent.java:864)
        at com.jagrosh.jdautilities.command.impl.CommandClientImpl.lambda$null$0(CommandClientImpl.java:170)
        at com.jagrosh.jdautilities.command.CommandEvent.lambda$sendMessage$19(CommandEvent.java:960)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by muxia9487** [comment]
About Emoij Error ,You can refer to my question

**Comment by muxia9487** [comment]
Use unicode encoding for your config file, and use valid emojis in the config for the success/warning/error emojis
